import React from "react";
import cyan from '../imgs/cyan.jpg';
import CircleLeft from '../svgs/circle-left.svg';
import CircleRight from '../svgs/circle-right.svg';
import EndCircle from '../svgs/end-circle.svg';
import STILogo1 from "../STI LOGOS/STI LOGO1.png";

export function TitleSlide({ title, subtitle }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-cyan-50 via-white to-teal-50 overflow-hidden flex items-center">
      <img
        src={STILogo1}
        alt="STI LOGO1"
        className="absolute top-8 right-8 w-40 h-auto pointer-events-none select-none"
      />
      {/* Soft overlapping shapes */}
      <div className="absolute top-[-100px] left-[-100px] w-[600px] h-[600px] bg-cyan-200/40 rounded-full blur-2xl"></div>
      <div className="absolute bottom-[-150px] right-[-150px] w-[800px] h-[800px] bg-teal-300/30 rounded-full blur-3xl"></div>

      {/* Layered geometric accents */}
      <div className="absolute top-1/3 left-1/4 w-48 h-48 bg-cyan-300/20 rotate-12 rounded-3xl"></div>
      <div className="absolute bottom-1/4 right-1/3 w-32 h-32 bg-teal-400/20 -rotate-12 rounded-3xl"></div>

      {/* Decorative dotted ring */}
      <div className="absolute left-[300px] top-[200px] w-[600px] h-[600px] border-dotted border-[8px] border-cyan-300/40 rounded-full"></div>

      {/* Content */}
      <div className="relative z-10 ml-32">
        <h1 className="text-7xl font-bold text-gray-800 mb-4">{title}</h1>
        {subtitle && (
          <p className="text-4xl text-gray-600 max-w-3xl">{subtitle}</p>
        )}
      </div>
    </section>
  );
}

export function MainSlide({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-white overflow-hidden flex items-center justify-between p-10">
      {/* Left shapes */}
      <img src={CircleLeft} alt="circle" className="absolute left-0 top-0 w-[500px]" />
      <img src={CircleRight} alt="shape" className="absolute bottom-0 right-0 w-[350px]" />

      <div className="relative z-10 w-1/2 bg-white shadow-lg rounded-lg p-8 ml-[300px]">
        <h2 className="text-6xl font-semibold text-gray-800 mb-4">{title}</h2>
        <p className="text-[2.7rem] text-gray-700 leading-relaxed">{content}</p>
      </div>
    </section>
  );
}

export function MainSlide1({ title, content, autoGeneratedImage }) {
  return (
    <section className="w-[1920px] h-[1080px] bg-cyan-200 flex items-center justify-center">
      <div className="w-5/6 h-5/6 flex items-center">
        {/* Left: auto image or placeholder for 2nd term */}
        <div className="w-1/2 h-full flex items-center justify-center pr-8">
          {autoGeneratedImage ? (
            <img
              src={autoGeneratedImage}
              alt={title}
              className="w-full h-full object-cover rounded-xl border-8 border-cyan-500/60 shadow-2xl"
            />
          ) : (
            <div className="w-4/5 h-4/5 bg-white/70 border-8 border-cyan-400/70 rounded-xl flex flex-col items-center justify-center">
              <div className="text-cyan-700 text-2xl font-bold mb-3">Auto Image Placeholder</div>
              <span className="text-cyan-700 text-lg">2nd Term MainSlide</span>
            </div>
          )}
        </div>

        {/* Right: title and content */}
        <div className="w-1/2 bg-white shadow-lg rounded-lg p-10">
          <h2 className="text-6xl font-bold text-gray-800 mb-4">{title}</h2>
          <p className="text-[2.5rem] text-gray-700 leading-relaxed">{content}</p>
        </div>
      </div>
    </section>
  );
}

export function MainSlide2({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-cyan-50 via-white to-teal-50 overflow-hidden flex flex-col items-center justify-center">
      {/* Soft abstract blobs */}
      <div className="absolute top-[-150px] left-[-100px] w-[600px] h-[600px] bg-cyan-300/30 rounded-full blur-3xl"></div>
      <div className="absolute bottom-[-200px] right-[-100px] w-[700px] h-[700px] bg-teal-400/20 rounded-full blur-2xl"></div>

      {/* Top Half: First Term */}
      <div className="absolute top-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full bg-white shadow-lg rounded-lg border-2 border-cyan-300 p-8 flex flex-col justify-center">
          <h2 className="text-6xl font-bold text-cyan-800 mb-6">{title || 'Term 1'}</h2>
          <div className="h-[3px] w-32 bg-cyan-500 mb-4 rounded-full"></div>
          <p className="text-[2.5rem] text-gray-700 leading-relaxed">{content || 'Definition for term 1'}</p>
        </div>
      </div>

      {/* Bottom Half: Second Term */}
      <div className="absolute bottom-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full bg-white shadow-lg rounded-lg border-2 border-teal-400 p-8 flex flex-col justify-center">
          <h2 className="text-6xl font-bold text-teal-800 mb-6">{title2 || 'Term 2'}</h2>
          <div className="h-[3px] w-32 bg-teal-500 mb-4 rounded-full"></div>
          <p className="text-[2.5rem] text-gray-700 leading-relaxed">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>
    </section>
  );
}


export function MainSlide3({ title, content }) {
  return (
    <section className="w-[1920px] h-[1080px] flex overflow-hidden">
      {/* Left content area (70%) */}
      <div className="w-[70%] bg-cyan-100 flex flex-col justify-center px-20 relative">
        {/* Soft blob background accent */}
        <div className="absolute top-[-100px] left-[-150px] w-[500px] h-[500px] bg-cyan-300 rounded-full blur-3xl opacity-40"></div>

        <h2 className="text-7xl font-semibold text-gray-800 mb-8 relative z-10">{title}</h2>
        <p className="text-[2.7rem] text-gray-700 leading-relaxed max-w-3xl relative z-10">
          {content}
        </p>
      </div>

      {/* Right image area (30%) */}
      <div className="w-[30%] bg-white flex items-center justify-center relative overflow-hidden">
        {/* Placeholder or image */}
        <img
          src={cyan}
          alt="Illustration"
          className="max-w-full h-full object-cover"
        />

        {/* Decorative shape */}
        <div className="absolute bottom-[-100px] right-[-100px] w-[300px] h-[300px] bg-cyan-300 rounded-full blur-2xl opacity-30"></div>
      </div>
    </section>
  );
}


export function MainSlide4({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex items-center justify-center bg-white">
      {/* Left: First Term */}
      <div className="absolute left-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="bg-white shadow-lg rounded-lg border-2 border-cyan-400 p-10">
          <h3 className="text-6xl font-semibold text-cyan-800 mb-6">{title || 'Term 1'}</h3>
          <div className="h-[3px] w-32 bg-cyan-500 mb-6 rounded-full"></div>
          <p className="text-[2.5rem] text-gray-700 leading-relaxed">{content || 'Definition for term 1'}</p>
        </div>
      </div>

      {/* Right: Second Term */}
      <div className="absolute right-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="bg-[#2c3e50] shadow-lg rounded-lg border-2 border-teal-500 p-10">
          <h3 className="text-6xl font-semibold text-white mb-6">{title2 || 'Term 2'}</h3>
          <div className="h-[3px] w-32 bg-teal-400 mb-6 rounded-full"></div>
          <p className="text-[2.6rem] text-white leading-relaxed">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>
    </section>
  );
}

/* Main Slide 5 – Angled split diagonal layout */
export function MainSlide5({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-cyan-100 via-white to-cyan-200 flex items-center justify-center overflow-hidden">
      {/* Blurred ambient blobs */}
      <div className="absolute -top-40 -left-40 w-[600px] h-[600px] bg-cyan-300/30 rounded-full blur-[120px]"></div>
      <div className="absolute bottom-0 right-0 w-[500px] h-[500px] bg-[#2c3e50]/20 rounded-full blur-[100px]"></div>

      {/* Glassy floating card */}
      <div className="relative z-10 backdrop-blur-3xl bg-white/10 border border-white/30 shadow-[0_0_40px_rgba(0,0,0,0.1)] rounded-[40px] px-24 py-20 text-center max-w-5xl">
        <h2 className="text-7xl font-semibold text-gray-900 mb-10 drop-shadow-sm">
          {title}
        </h2>
        <p className="text-[2.7rem] text-gray-800/90 leading-relaxed">
          {content}
        </p>

        {/* Glass highlight edge */}
        <div className="absolute inset-0 rounded-[40px] bg-gradient-to-br from-white/40 to-transparent opacity-30 pointer-events-none"></div>
      </div>

      {/* Subtle light reflection layer */}
      <div className="absolute inset-0 bg-gradient-to-t from-white/10 via-transparent to-white/30 opacity-60 mix-blend-overlay pointer-events-none"></div>
    </section>
  );
}


/* Main Slide 6 – Circle focal point layout */
export function MainSlide6({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-white flex items-center justify-center overflow-hidden">
      {/* Big background circle */}
      <div className="absolute w-[900px] h-[900px] rounded-full bg-cyan-200 opacity-50"></div>
      <div className="absolute w-[600px] h-[600px] rounded-full bg-[#2c3e50]/40"></div>

      {/* Overlay shapes */}
      <div className="absolute top-16 left-16 w-32 h-32 bg-cyan-400/40 rounded-full"></div>
      <div className="absolute bottom-16 right-32 w-40 h-40 bg-cyan-300/40 rounded-full"></div>

      {/* Content centered inside circle */}
      <div className="relative z-10 max-w-4xl text-center">
        <h2 className="text-7xl font-semibold text-gray-800 mb-6">{title}</h2>
        <p className="text-[2.7rem] text-gray-700 leading-relaxed">{content}</p>
      </div>
    </section>
  );
}



export function TOCSlide({ tocData }) {
  // Handle both old format (items array) and new format (tocData object)
  const title = tocData?.title || "Table of Contents";
  const sections = tocData?.sections || [];
  
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-[#e0f7fa] via-[#b2ebf2] to-[#80deea] text-[#044e54] flex flex-col items-center justify-center overflow-hidden">
      {/* Background soft waves */}
      <div className="absolute bottom-0 w-full h-64 bg-gradient-to-t from-cyan-600/30 to-transparent rounded-t-[100%]"></div>
      <div className="absolute top-0 w-full h-48 bg-gradient-to-b from-cyan-400/20 to-transparent rounded-b-[100%]"></div>

      {/* Decorative circles */}
      <div className="absolute top-20 left-20 w-40 h-40 rounded-full bg-cyan-300/30 blur-2xl"></div>
      <div className="absolute bottom-20 right-20 w-56 h-56 rounded-full bg-teal-400/30 blur-2xl"></div>

      {/* Title */}
      <h2 className="text-6xl font-bold mb-16 tracking-wide text-cyan-900 drop-shadow-sm">
        {title}
      </h2>

      {/* Two-Column Layout for TOC - Minimized to show only main sections */}
      <div className="grid grid-cols-2 gap-20 z-10 max-w-6xl w-full">
        {/* Left Column */}
        <div className="space-y-10">
          {sections.slice(0, Math.ceil(sections.length / 2)).map((section, sectionIndex) => (
            <div key={sectionIndex} className="flex items-center gap-8 text-gray-800 hover:text-cyan-600 transition-colors duration-300 group">
              <div className="w-20 h-20 flex items-center justify-center rounded-full bg-cyan-500 group-hover:bg-cyan-600 text-white text-2xl font-bold flex-shrink-0 border-3 border-cyan-200 group-hover:border-cyan-300 shadow-lg transition-all duration-300">
                {sectionIndex + 1}
              </div>
              <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div className="space-y-10">
          {sections.slice(Math.ceil(sections.length / 2)).map((section, sectionIndex) => {
            const actualIndex = Math.ceil(sections.length / 2) + sectionIndex;
            return (
              <div key={actualIndex} className="flex items-center gap-8 text-gray-800 hover:text-cyan-600 transition-colors duration-300 group">
                <div className="w-20 h-20 flex items-center justify-center rounded-full bg-cyan-500 group-hover:bg-cyan-600 text-white text-2xl font-bold flex-shrink-0 border-3 border-cyan-200 group-hover:border-cyan-300 shadow-lg transition-all duration-300">
                  {actualIndex + 1}
                </div>
                <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

// Keep old component for backward compatibility
export function TOCSlideCalmCyan({ title = "Table of Contents", items = [] }) {
  const tocData = {
    title,
    sections: items.map(item => ({ title: item, subsections: [] }))
  };
  return <TOCSlide tocData={tocData} />;
}

const CalmCyan = { 
  TitleSlide, 
  TOCSlide, 
  MainSlide, 
  MainSlide1,
  MainSlide2,
  MainSlide3,
  MainSlide4,
  MainSlide5,
  MainSlide6,
  ImageSlide,
  EndSlide 
};
export default CalmCyan;

export function EndSlide() {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#2c3e50] flex items-center justify-center">
      <img src={EndCircle} alt="circle" className="absolute w-[700px]" />
      <div className="relative z-10 text-center text-black">
        <h1 className="text-6xl font-bold mb-4">Thank You!</h1>
        <p className="text-xl">End of Presentation</p>
      </div>
    </section>
  );
}


/* ---------------- IMAGE SLIDE ---------------- */
export function ImageSlide({ title, content, autoGeneratedImage, imageUrl }) {
  const imageSrc = autoGeneratedImage || imageUrl;
  return (
    <section className="relative w-[1920px] h-[1080px] bg-white overflow-hidden flex items-center justify-between p-10">
      {/* Left shapes */}
      <img src={CircleLeft} alt="circle" className="absolute left-0 top-0 w-[500px]" />
      <img src={CircleRight} alt="shape" className="absolute bottom-0 right-0 w-[350px]" />

      <div className="relative z-10 w-full h-5/6 flex items-center justify-between">
        {/* Left: auto image or placeholder for 1st term */}
        <div className="w-1/2 h-full flex items-center justify-center pr-8">
          {imageSrc ? (
            <img
              src={imageSrc}
              alt={title}
              className="max-w-full max-h-full object-contain rounded-xl border-8 border-cyan-500/60 shadow-2xl bg-white"
            />
          ) : (
            <div className="w-4/5 h-4/5 bg-white/80 border-8 border-cyan-400/70 rounded-xl flex flex-col items-center justify-center">
              <div className="text-cyan-700 text-2xl font-bold mb-3">Auto Image Placeholder</div>
              <span className="text-cyan-700 text-lg">1st Term ImageSlide</span>
            </div>
          )}
        </div>

        {/* Right: title and definition */}
        <div className="w-1/2 bg-white shadow-lg rounded-lg p-10 ml-8">
          {title && <h2 className="text-6xl font-semibold text-gray-800 mb-4">{title}</h2>}
          {content && <p className="text-2xl text-gray-700 leading-relaxed">{content}</p>}
        </div>
      </div>
    </section>
  );
}
