import React from "react";
import { Pencil, BookOpen, Ruler, Sigma, Apple, GraduationCap, Book } from "lucide-react";
import Classroom1Png from '../pngs/classroom1.png';
import Classroom1Svg from '../svgs/classroom1.svg';
import STILogo1 from "../STI LOGOS/STI LOGO1.png";


export function TitleSlide({ title, subtitle }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-[#2f4f2f] to-[#1e3d1e] flex items-center justify-center text-center text-white overflow-hidden shadow-inner">
      <img
        src={STILogo1}
        alt="STI LOGO1"
        className="absolute top-8 right-8 w-40 h-auto pointer-events-none select-none z-50"
      />
      <div className="absolute inset-0 bg-gradient-to-br from-[#2f3e46] to-[#1c2529]"></div>
      <div className="absolute inset-0 opacity-20 bg-[url('https://www.transparenttextures.com/patterns/asfalt-light.png')]"></div>

      <div className="absolute inset-0 border-[40px] border-[#5d4037] rounded-xl shadow-2xl"></div>
      <div className="relative z-10 px-12">
        <h1 className="font-chalkTitle text-8xl leading-tight text-[#EAD7B7] mb-4 drop-shadow-lg">
          {title}
        </h1>
        {subtitle && (
          <p className="font-chalk-sub text-[#f0f0e1] opacity-90">
            {subtitle}
          </p>
        )}
      </div>
    </section>
  );
}

export function TOCSlide({ tocData }) {
  // Handle both old format (items array) and new format (tocData object)
  const title = tocData?.title || "Table of Contents";
  const sections = tocData?.sections || [];
  
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#2f3e46] text-white flex flex-col items-center justify-center overflow-hidden">
      {/* Chalkboard background effect */}
      <div className="absolute inset-0 bg-gradient-to-br from-[#2f3e46] to-[#1c2529]"></div>
      <div className="absolute inset-0 opacity-20 bg-[url('https://www.transparenttextures.com/patterns/asfalt-light.png')]"></div>

      {/* Wooden frame */}
      <div className="absolute inset-0 border-[20px] border-[#5d4037] rounded-xl shadow-2xl"></div>

      {/* Title */}
      <h2 className="text-6xl font-bold text-[#EAD7B7] mb-16 drop-shadow-lg font-serif z-10">
        {title}
      </h2>

      {/* Two-Column Layout for TOC - Minimized to show only main sections */}
      <div className="grid grid-cols-2 gap-20 z-10 max-w-6xl w-full">
        {/* Left Column */}
        <div className="space-y-10">
          {sections.slice(0, Math.ceil(sections.length / 2)).map((section, sectionIndex) => (
            <div key={sectionIndex} className="flex items-center gap-8 text-[#EAD7B7] hover:text-[#F5E6A3] transition-colors duration-300 group">
              <div className={`w-20 h-20 flex items-center justify-center rounded-full text-white text-2xl font-bold flex-shrink-0 border-3 border-[#EAD7B7]/40 group-hover:border-[#F5E6A3]/60 transition-all duration-300 shadow-lg
                ${sectionIndex % 4 === 0 ? "bg-[#5d4037]" : sectionIndex % 4 === 1 ? "bg-[#8d6e63]" : sectionIndex % 4 === 2 ? "bg-[#a1887f]" : "bg-[#bcaaa4]"}`}>
                {sectionIndex + 1}
              </div>
              <span className="text-5xl font-bold text-left leading-tight flex-1 font-serif group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div className="space-y-10">
          {sections.slice(Math.ceil(sections.length / 2)).map((section, sectionIndex) => {
            const actualIndex = Math.ceil(sections.length / 2) + sectionIndex;
            return (
              <div key={actualIndex} className="flex items-center gap-8 text-[#EAD7B7] hover:text-[#F5E6A3] transition-colors duration-300 group">
                <div className={`w-20 h-20 flex items-center justify-center rounded-full text-white text-2xl font-bold flex-shrink-0 border-3 border-[#EAD7B7]/40 group-hover:border-[#F5E6A3]/60 transition-all duration-300 shadow-lg
                  ${actualIndex % 4 === 0 ? "bg-[#5d4037]" : actualIndex % 4 === 1 ? "bg-[#8d6e63]" : actualIndex % 4 === 2 ? "bg-[#a1887f]" : "bg-[#bcaaa4]"}`}>
                  {actualIndex + 1}
                </div>
                <span className="text-5xl font-bold text-left leading-tight flex-1 font-serif group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}


export function MainSlide({ title, content, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#0D3B36] text-white flex items-center justify-center overflow-hidden">
      <div className="absolute inset-0 border-[30px] border-[#5d4037] rounded-xl shadow-2xl" />

      <div className="absolute inset-0 bg-gradient-to-br from-[#2f3e46] to-[#1c2529]" />

      {/* Subtle classroom icons */}
      <Book className="absolute top-16 left-24 w-28 h-28 text-white/10 rotate-[-15deg]" />
      <Pencil className="absolute bottom-24 right-40 w-24 h-24 text-white/10 rotate-[20deg]" />
      <Ruler className="absolute top-1/3 right-16 w-28 h-28 text-white/10 rotate-[45deg]" />
      <Apple className="absolute bottom-16 left-40 w-24 h-24 text-white/10" />
      <GraduationCap className="absolute top-1/4 left-1/2 w-28 h-28 text-white/10 -translate-x-1/2" />

      {/* Main content area with auto-generated image support */}
      <div className="relative z-10 w-full h-full flex items-center justify-center">
        {/* Left side: Auto-generated image placeholder for 1st term */}
        <div className="w-1/2 h-4/5 flex items-center justify-center px-8">
          {autoGeneratedImage ? (
            <img 
              src={autoGeneratedImage} 
              alt={title} 
              className="w-full h-full object-cover rounded-lg border-4 border-[#EAD7B7] shadow-2xl" 
            />
          ) : (
            <div className="w-full h-full bg-[#EAD7B7]/10 border-4 border-[#EAD7B7] rounded-lg flex flex-col items-center justify-center">
              <div className="text-[#EAD7B7] text-3xl font-bold mb-4">Auto Image Placeholder</div>
              <span className="text-[#EAD7B7] text-xl text-center px-4">1st Term: {title}</span>
            </div>
          )}
        </div>
        
        {/* Right side: Term and definition */}
        <div className="w-1/2 bg-[#0D3B36] border-4 border-[#EAD7B7] rounded-lg p-8 text-center shadow-lg mx-8">
          <h2 className="font-chalkTitle text-6xl mb-4">{title}</h2>
          <p className="text-4xl text-chalk-sub leading-relaxed">{content}</p>
        </div>
      </div>
    </section>
  );
}

export function MainSlide2({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#0D3B36] text-white flex flex-col items-center justify-center overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-br from-[#2f3e46] to-[#1c2529]"></div>
      <div className="absolute inset-0 opacity-20 bg-[url('https://www.transparenttextures.com/patterns/asfalt-light.png')]"></div>

      <div className="absolute inset-0 border-[40px] border-[#5d4037] rounded-xl shadow-2xl"></div>

      {/* Chalk-style background icons */}
      <Pencil className="absolute top-20 left-20 w-24 h-24 text-[#EAD7B7]/20" />
      <BookOpen className="absolute bottom-24 left-40 w-28 h-28 text-[#EAD7B7]/20" />
      <Sigma className="absolute top-32 right-32 w-28 h-28 text-[#EAD7B7]/20" />
      <Ruler className="absolute bottom-32 right-16 w-28 h-28 text-[#EAD7B7]/20" />

      {/* Top Half: First Term */}
      <div className="absolute top-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="bg-[#1c2b23]/90 border-4 border-[#EAD7B7] rounded-lg p-8 h-full flex flex-col justify-center shadow-2xl">
          <h2 className="font-chalkTitle text-7xl text-[#EAD7B7] mb-6">{title || 'Term 1'}</h2>
          <p className="text-4xl text-[#EAD7B7] leading-relaxed">{content || 'Definition for term 1'}</p>
        </div>
      </div>
      
      {/* Bottom Half: Second Term */}
      <div className="absolute bottom-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="bg-[#1c2b23]/90 border-4 border-[#EAD7B7] rounded-lg p-8 h-full flex flex-col justify-center shadow-2xl">
          <h2 className="font-chalkTitle text-7xl text-[#EAD7B7] mb-6">{title2 || 'Term 2'}</h2>
          <p className="text-4xl text-[#EAD7B7] leading-relaxed">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>
    </section>
  );
}

export function MainSlide3({ title, content, imageUrl }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#0D3B36] text-white flex items-center overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-br from-[#2f3e46] to-[#1c2529]"></div>
      <div className="absolute inset-0 opacity-20 bg-[url('https://www.transparenttextures.com/patterns/asfalt-light.png')]"></div>

      <div className="absolute inset-0 border-[40px] border-[#5d4037] rounded-xl shadow-2xl"></div>

      {/* Chalk-style background icons */}
      <Pencil className="absolute top-20 left-20 w-24 h-24 text-[#EAD7B7]/20" />
      <BookOpen className="absolute bottom-24 left-40 w-28 h-28 text-[#EAD7B7]/20" />
      <Sigma className="absolute top-32 right-32 w-28 h-28 text-[#EAD7B7]/20" />
      <Ruler className="absolute bottom-32 right-16 w-28 h-28 text-[#EAD7B7]/20" />

      <div className="relative z-10 w-1/2 p-8 text-left translate-x-[150px]">
        <h2 className="font-chalkTitle text-[#EAD7B7] text-8xl mb-4 translate-y-[-100px]">{title}</h2>
        <p className="text-5xl text-chalk-sub text-[#EAD7B7] leading-relaxed">{content}</p>
      </div>
      <div className="relative mr-20 z-10 w-[600px] h-4/5flex translate-x-[200px] items-center justify-center">
        <img src={Classroom1Svg} alt="classroom1" crossOrigin="anonymous" onError={(e)=>{ e.currentTarget.onerror=null; e.currentTarget.src=Classroom1Png; }} />
      </div>
    </section>
  );
}

export function MainSlide4({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#fdfcf5] flex items-center justify-center overflow-hidden shadow-2xl">
       <div className="absolute inset-0 border-[40px] border-[#5d4037] rounded-xl shadow-2xl"></div>
      {/* Notebook background: blue horizontal lines + red margin */}
      <div className="absolute inset-0 bg-[linear-gradient(to_bottom,transparent_95%,#c3d1e3_95%)] bg-[length:100%_40px]"></div>
      <div className="absolute top-0 left-[120px] w-[2px] h-full bg-[#e56b6f]/80"></div>
      <div className="absolute top-0 left-1/2 w-[2px] h-full bg-[#e56b6f]/80"></div>

      {/* Chalk-style margin doodles */}
      <Pencil className="absolute top-24 left-16 w-24 h-24 text-[#3b3b3b]/80" />
      <BookOpen className="absolute bottom-24 left-24 w-28 h-28 text-[#3b3b3b]/80" />
      <Sigma className="absolute top-32 right-32 w-28 h-28 text-[#3b3b3b]/80" />
      <Ruler className="absolute bottom-32 right-16 w-28 h-28 text-[#3b3b3b]/80" />

      {/* Notebook binder rings */}
      <div className="absolute top-12 left-10 flex flex-col gap-10">
        {Array.from({ length: 10 }).map((_, i) => (
          <div
            key={i}
            className="w-6 h-6 rounded-full border-[3px] border-[#9e9e9e]/70 bg-[#fefcf7]"
          />
        ))}
      </div>

      {/* Left Half: First Term */}
      <div className="absolute left-[150px] top-1/2 -translate-y-1/2 w-[700px] z-10">
        <h2 className="font-['Schoolbell'] text-7xl text-[#2e2e2e] mb-6 tracking-wide">
          {title || 'Term 1'}
        </h2>
        <p className="font-['Gloria_Hallelujah'] text-5xl text-[#3a3a3a] leading-relaxed">
          {content || 'Definition for term 1'}
        </p>
      </div>
      
      {/* Right Half: Second Term */}
      <div className="absolute right-[100px] top-1/2 -translate-y-1/2 w-[700px] z-10">
        <h2 className="font-['Schoolbell'] text-7xl text-[#2e2e2e] mb-6 tracking-wide">
          {title2 || 'Term 2'}
        </h2>
        <p className="font-['Gloria_Hallelujah'] text-5xl text-[#3a3a3a] leading-relaxed">
          {content2 || 'Definition for term 2'}
        </p>
      </div>
    </section>
  );
}



export function ImageSlide({ title, content, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#0D3B36] flex items-center justify-center overflow-hidden">
      <div className="absolute inset-0 border-[30px] border-[#5d4037] rounded-xl shadow-2xl" />

      {/* Chalk-style background icons */}
      <Pencil className="absolute top-20 left-20 w-24 h-24 text-[#EAD7B7]/20" />
      <BookOpen className="absolute bottom-24 left-40 w-28 h-28 text-[#EAD7B7]/20" />
      <Sigma className="absolute top-32 right-32 w-28 h-28 text-[#EAD7B7]/20" />
      <Ruler className="absolute bottom-32 right-16 w-28 h-28 text-[#EAD7B7]/20" />

      <div className="relative z-10 w-5/6 h-5/6 flex items-center justify-between">
        {/* Left side: Auto-generated image placeholder for 1st term */}
        <div className="w-1/2 h-full flex items-center justify-center pr-8">
          {autoGeneratedImage ? (
            <img 
              src={autoGeneratedImage} 
              alt={title} 
              className="max-w-full max-h-full object-contain rounded-lg border-4 border-[#EAD7B7] shadow-2xl" 
            />
          ) : (
            <div className="w-4/5 h-4/5 bg-[#EAD7B7]/10 border-4 border-[#EAD7B7] rounded-lg flex flex-col items-center justify-center">
              <div className="text-[#EAD7B7] text-3xl font-bold mb-4">🎨 Auto Image Placeholder</div>
              <span className="text-[#EAD7B7] text-xl text-center px-4">1st Term: {title}</span>
            </div>
          )}
        </div>
        
        {/* Right side: Term and definition */}
        <div className="w-1/2 text-white px-8">
          {title && <h2 className="font-[HedvigLettersSerif] text-8xl mb-8">{title}</h2>}
          {content && <p className="text-5xl leading-relaxed">{content}</p>}
        </div>
      </div>
    </section>
  );
}

export function MainSlide6({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#f1e8d9] flex items-center justify-center overflow-hidden">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_60%,rgba(0,0,0,0.25)_100%)] pointer-events-none"></div>

      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/paper-fibers.png')] opacity-50"></div>

      <div className="relative z-10 w-[1400px] h-[800px] bg-[#1c2b23] border-[40px] border-[#5d4037] rounded-[20px] shadow-[0_20px_40px_rgba(0,0,0,0.5)] flex flex-col items-center justify-center text-center px-20">
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/dust.png')] opacity-20 pointer-events-none"></div>

        <Pencil className="absolute top-12 left-12 w-16 h-16 text-white/15" />
        <BookOpen className="absolute bottom-20 left-24 w-20 h-20 text-white/15" />
        <Sigma className="absolute top-20 right-24 w-20 h-20 text-white/15" />
        <Ruler className="absolute bottom-12 right-16 w-20 h-20 text-white/15" />

        <h2 className="font-['Schoolbell'] text-white text-7xl mb-8 animate-fade-in drop-shadow-lg">
          {title || "Lesson Recap"}
        </h2>
        <p className="font-['Gloria_Hallelujah'] text-white/90 text-4xl leading-relaxed max-w-5xl animate-slide-up">
          {content ||
            "A summary of what we learned today, neatly written on the classroom chalkboard for review."}
        </p>
      </div>

      <div className="absolute bottom-0 w-full h-[200px] bg-[url('https://www.transparenttextures.com/patterns/wood-pattern.png')] bg-[#8d6e63] border-t-[10px] border-[#5d4037] shadow-inner"></div>

      <div className="absolute top-10 left-1/2 -translate-x-1/2 flex gap-4">
        <div className="w-6 h-6 bg-red-500 rounded-full shadow-md"></div>
        <div className="w-6 h-6 bg-yellow-400 rounded-full shadow-md"></div>
        <div className="w-6 h-6 bg-blue-500 rounded-full shadow-md"></div>
      </div>
    </section>
  );
}




export function EndSlide() {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#0D3B36] flex items-center justify-center text-white overflow-hidden">

      <div className="absolute inset-0 border-[30px] border-[#5d4037] rounded-xl shadow-2xl" />

      {/* Chalk-style icons */}
      <Book className="absolute top-16 left-24 w-28 h-28 text-white/10 rotate-[-15deg]" />
      <Pencil className="absolute bottom-24 right-40 w-24 h-24 text-white/10 rotate-[20deg]" />
      <Ruler className="absolute top-1/3 right-16 w-28 h-28 text-white/10 rotate-[45deg]" />
      <Apple className="absolute bottom-16 left-40 w-24 h-24 text-white/10" />
      <GraduationCap className="absolute top-1/4 left-1/2 w-28 h-28 text-white/10 -translate-x-1/2" />

      <h1 className="relative z-10 font-[HedvigLettersSerif] text-8xl">Thank You</h1>
    </section>
  );
}

// Keep old component for backward compatibility
export function TOCSlideClassicClassroom({ title = "Table of Contents", items = [] }) {
  const tocData = {
    title,
    sections: items.map(item => ({ title: item, subsections: [] }))
  };
  return <TOCSlide tocData={tocData} />;
}

const ClassicClassroom = { TitleSlide, 
                         TOCSlide,
                         ImageSlide,
                         MainSlide, 
                         MainSlide2, 
                         MainSlide3, 
                         MainSlide4, 
                         MainSlide6,
                         EndSlide };
export default ClassicClassroom;
