import React from "react";
import Elearning1 from '../svgs/Elearning1.svg';
import STILogo1 from "../STI LOGOS/STI LOGO1.png";

/* Title Slide – Chalkboard with center text + doodles */
export function TitleSlide({ title, subtitle }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#1b1b1b] text-white flex flex-col items-center justify-center overflow-hidden">
      <img
        src={STILogo1}
        alt="STI LOGO1"
        className="absolute top-8 right-8 w-40 h-auto pointer-events-none select-none"
      />
      {/* Chalk smudge border */}
      <div className="absolute inset-4 border-[6px] border-green-400/60 rounded-xl opacity-50"></div>

      {/* Chalk doodles */}
      <div className="absolute top-10 left-16 text-pink-400/70 text-5xl">✏️</div>
      <div className="absolute bottom-14 right-20 text-yellow-300/70 text-4xl">★</div>
      <div className="absolute top-1/3 left-1/4 text-cyan-300/60 text-6xl">+</div>

      {/* Title */}
      <h1 className="text-7xl font-bold font-mono text-green-200 mb-4 drop-shadow-lg">
        {title}
      </h1>
      <h2 className="text-2xl font-mono text-gray-200">{subtitle}</h2>
    </section>
  );
}

/* Table of Contents Slide – Digital Chalkboard */
export function TOCSlide({ tocData }) {
  // Handle both old format (items array) and new format (tocData object)
  const title = tocData?.title || "Table of Contents";
  const sections = tocData?.sections || [];
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#1b1b1b] text-white flex flex-col items-center justify-center overflow-hidden">
      {/* Chalk smudge border */}
      <div className="absolute inset-8 border-[6px] border-green-400/60 rounded-xl opacity-60"></div>

      {/* Chalk doodles */}
      <div className="absolute top-20 left-24 text-yellow-300/70 text-5xl">★</div>
      <div className="absolute bottom-24 right-24 text-pink-400/70 text-4xl">✏️</div>
      <div className="absolute top-2/3 left-12 text-cyan-300/60 text-5xl">+</div>

      {/* Title */}
      <h2 className="text-6xl font-mono font-bold text-green-300 mb-16 drop-shadow-lg">
        {title}
      </h2>

      {/* Two-Column Layout for TOC - Minimized to show only main sections */}
      <div className="grid grid-cols-2 gap-20 z-10 max-w-6xl w-full">
        {/* Left Column */}
        <div className="space-y-10">
          {sections.slice(0, Math.ceil(sections.length / 2)).map((section, sectionIndex) => (
            <div key={sectionIndex} className="flex items-center gap-8 hover:text-yellow-300 transition-colors duration-300 group">
              <span className="w-20 h-20 flex items-center justify-center rounded-full border-3 border-green-400/40 group-hover:border-green-300/60 text-green-300 text-2xl font-bold flex-shrink-0 bg-green-400/10 group-hover:bg-green-400/20 transition-all duration-300 shadow-lg">
                {sectionIndex + 1}
              </span>
              <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div className="space-y-10">
          {sections.slice(Math.ceil(sections.length / 2)).map((section, sectionIndex) => {
            const actualIndex = Math.ceil(sections.length / 2) + sectionIndex;
            return (
              <div key={actualIndex} className="flex items-center gap-8 hover:text-yellow-300 transition-colors duration-300 group">
                <span className="w-20 h-20 flex items-center justify-center rounded-full border-3 border-green-400/40 group-hover:border-green-300/60 text-green-300 text-2xl font-bold flex-shrink-0 bg-green-400/10 group-hover:bg-green-400/20 transition-all duration-300 shadow-lg">
                  {actualIndex + 1}
                </span>
                <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}


/* Main Slide 1 – Left title bar, chalk text on right */
export function MainSlide1({ title, content, imageUrl, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#2a2a2a] text-white flex items-center justify-between px-16">
      
      {/* Left side: Auto-generated image placeholder for 2nd term */}
      <div className="w-1/2 h-full flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain rounded-lg shadow-lg border-4 border-white/20" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-[#1b1b1b] border-4 border-green-400/70 rounded-lg flex flex-col items-center justify-center shadow-lg">
            <div className="text-green-300 text-3xl font-mono font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-yellow-300 text-xl text-center px-4 font-mono">2nd Term: {title}</span>
          </div>
        )}
      </div>

      {/* Right side: Term and definition */}
      <div className="w-1/2 pl-12">
        <div className="bg-[#1b1b1b] border-4 border-green-400/40 rounded-lg p-8">
          <h2 className="text-6xl font-mono text-green-300 mb-6 -rotate-1">{title}</h2>
          <div className="h-[3px] w-40 bg-green-400 mb-6 -rotate-1"></div>
          {content && (
            <div className="bg-[#2a2a2a]/60 border-l-4 border-yellow-300 p-6 rounded-r-lg">
              <p className="text-[2.5rem] font-mono leading-relaxed text-gray-200 whitespace-pre-line">
                {content}
              </p>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}

/* Main Slide 2 – Top title, chalk underline, centered content */
export function MainSlide2({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#050505] flex flex-col items-center justify-center overflow-hidden font-mono text-white">
      {/* Holographic glow background */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(0,255,255,0.08)_0%,transparent_70%)]"></div>

      {/* Scanning line animation */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-cyan-400/10 to-transparent animate-scan"></div>

      {/* Hologram grid */}
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(0,255,255,0.08)_1px,transparent_1px),linear-gradient(rgba(0,255,255,0.08)_1px,transparent_1px)] bg-[size:60px_60px] opacity-30"></div>

      {/* Top Half: First Term */}
      <div className="absolute top-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full bg-gradient-to-br from-cyan-400/10 to-cyan-200/5 backdrop-blur-[6px] border border-cyan-400/40 rounded-3xl shadow-[0_0_40px_rgba(0,255,255,0.15)] flex flex-col items-center justify-center p-8">
          <h2 className="text-6xl font-bold text-cyan-300 drop-shadow-[0_0_15px_rgba(0,255,255,0.5)] mb-6 tracking-tight">
            {title || 'Term 1'}
          </h2>
          <div className="w-[200px] h-[2px] bg-gradient-to-r from-cyan-400 via-blue-400 to-cyan-400 mb-6 shadow-[0_0_20px_rgba(0,255,255,0.5)]"></div>
          <p className="text-4xl leading-relaxed text-center text-cyan-100/90 tracking-wide">
            {content || 'Definition for term 1'}
          </p>
        </div>
      </div>

      {/* Bottom Half: Second Term */}
      <div className="absolute bottom-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full bg-gradient-to-br from-green-400/10 to-green-200/5 backdrop-blur-[6px] border border-green-400/40 rounded-3xl shadow-[0_0_40px_rgba(0,255,100,0.15)] flex flex-col items-center justify-center p-8">
          <h2 className="text-6xl font-bold text-green-300 drop-shadow-[0_0_15px_rgba(0,255,100,0.5)] mb-6 tracking-tight">
            {title2 || 'Term 2'}
          </h2>
          <div className="w-[200px] h-[2px] bg-gradient-to-r from-green-400 via-yellow-400 to-green-400 mb-6 shadow-[0_0_20px_rgba(0,255,100,0.5)]"></div>
          <p className="text-4xl leading-relaxed text-center text-green-100/90 tracking-wide">
            {content2 || 'Definition for term 2'}
          </p>
        </div>
      </div>

      {/* Corner data lines */}
      <div className="absolute top-16 left-16 w-24 h-[1px] bg-gradient-to-r from-cyan-400 to-transparent"></div>
      <div className="absolute top-16 left-16 w-[1px] h-24 bg-gradient-to-b from-cyan-400 to-transparent"></div>

      <div className="absolute bottom-16 right-16 w-24 h-[1px] bg-gradient-to-l from-cyan-400 to-transparent"></div>
      <div className="absolute bottom-16 right-16 w-[1px] h-24 bg-gradient-to-t from-cyan-400 to-transparent"></div>
    </section>
  );
}


/* Main Slide 3 – Chalkboard grid background, content left, doodle right */
export function MainSlide3({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#0e0e0e] text-white flex items-center justify-center overflow-hidden">
      {/* Subtle grid background */}
      <div className="absolute inset-0 opacity-20 bg-[linear-gradient(to_right,rgba(255,255,255,0.08)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,0.08)_1px,transparent_1px)] bg-[size:80px_80px]"></div>

      {/* Glow accents */}
      <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-cyan-500/20 blur-[200px]"></div>
      <div className="absolute bottom-0 right-0 w-[400px] h-[400px] bg-pink-500/10 blur-[180px]"></div>

      {/* Glass board container */}
      <div className="relative z-10 w-[75%] h-[70%] backdrop-blur-[12px] bg-white/10 border border-white/30 rounded-2xl shadow-[0_0_60px_rgba(0,255,255,0.15)] flex flex-col items-center justify-center p-20">
        {/* Decorative glowing edge lines */}
        <div className="absolute top-0 left-0 w-full h-[4px] bg-gradient-to-r from-cyan-400 to-transparent rounded-t-2xl opacity-70"></div>
        <div className="absolute bottom-0 left-0 w-full h-[4px] bg-gradient-to-l from-cyan-400 to-transparent rounded-b-2xl opacity-70"></div>

        {/* Title */}
        <h2 className="text-7xl font-mono font-bold text-cyan-300 mb-12 drop-shadow-[0_0_20px_rgba(0,255,255,0.5)]">
          {title}
        </h2>

        {/* Content */}
        <p className="text-[2.7rem] font-light font-mono text-gray-100/90 leading-relaxed max-w-5xl text-center">
          {content}
        </p>
      </div>
    </section>
  );
}


// Main Slide 4 – Orange Highlight
export function MainSlide4({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#1a1a1a] text-white overflow-hidden flex items-center justify-center">
      {/* Chalk smudge border */}
      <div className="absolute inset-8 border-[6px] border-yellow-400/60 rounded-xl opacity-60"></div>

      {/* Chalk doodles */}
      <div className="absolute top-20 left-20 text-6xl opacity-20">✏️</div>
      <div className="absolute bottom-20 right-24 text-6xl opacity-20">📐</div>

      {/* Left: First Term */}
      <div className="absolute left-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="bg-[#2a2a2a] border-4 border-green-400/70 rounded-lg p-10 shadow-lg">
          <h2 className="font-mono font-bold text-6xl mb-6 text-green-300">
            {title || 'Term 1'}
          </h2>
          <div className="h-[3px] w-32 bg-green-400 mb-4"></div>
          <p className="font-mono text-[2.5rem] leading-relaxed text-white/90">
            {content || 'Definition for term 1'}
          </p>
        </div>
      </div>

      {/* Right: Second Term */}
      <div className="absolute right-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="bg-[#2a2a2a] border-4 border-yellow-400/70 rounded-lg p-10 shadow-lg">
          <h2 className="font-mono font-bold text-6xl mb-6 text-yellow-300">
            {title2 || 'Term 2'}
          </h2>
          <div className="h-[3px] w-32 bg-yellow-400 mb-4"></div>
          <p className="font-mono text-[2.5rem] leading-relaxed text-white/90">
            {content2 || 'Definition for term 2'}
          </p>
        </div>
      </div>
    </section>
  );
}

// Main Slide 5 – Split Notes Chalkboard
export function MainSlide5({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#0D3B36] text-white flex items-center px-24 py-16 overflow-hidden">
      {/* Chalk Doodles */}
      <div className="absolute top-12 left-16 text-6xl opacity-20">📘</div>
      <div className="absolute bottom-16 right-20 text-6xl opacity-20">✒️</div>

      {/* Left column */}
      <div className="flex-1 pr-16 z-10">
        <h2 className="font-mono font-bold text-7xl mb-6 text-yellow-200">
          {title}
        </h2>
        <p className="font-mono text-[2.7rem] leading-relaxed text-white/90">{content}</p>
      </div>

      {/* Divider */}
      <div className="w-[3px] h-[70%] bg-yellow-300 opacity-70"></div>

      {/* Right column */}
      <div className="flex-1 pl-16 z-10">
        <img src={Elearning1} alt="Elearning1" className="w-[700px] border-none"/>
      </div>
    </section>
  );
}

// Main Slide 6 – Center Highlight Chalk Frame
export function MainSlide6({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#1b1b1b] flex items-center justify-center text-white px-24 py-20 overflow-hidden">
      {/* Chalkboard frame */}
      <div className="absolute inset-16 border-8 border-yellow-300 rounded-lg opacity-70"></div>

      {/* Chalk doodles */}
      <div className="absolute top-12 left-20 text-5xl opacity-20">⭐</div>
      <div className="absolute bottom-12 right-24 text-5xl opacity-20">📚</div>
      <div className="absolute top-1/3 right-1/3 text-4xl opacity-20">✏️</div>

      {/* Main text */}
      <div className="relative z-10 max-w-4xl text-center">
        <h2 className="font-mono font-bold text-7xl mb-8 text-yellow-200">
          {title}
        </h2>
        <p className="font-mono text-[2.7rem] leading-relaxed text-white/90">{content}</p>
      </div>
    </section>
  );
}


/* Image Slide – Chalk border with image inside */
export function ImageSlide({ title, content, imageUrl, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#1b1b1b] text-white flex items-center justify-between px-16">
      <div className="absolute inset-6 border-4 border-cyan-400/70 rounded-lg opacity-60"></div>
      
      {/* Left side: Auto-generated image placeholder for 1st term */}
      <div className="relative z-10 w-1/2 h-full flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain rounded-lg shadow-lg border-4 border-white/20" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-[#2a2a2a] border-4 border-cyan-400/70 rounded-lg flex flex-col items-center justify-center shadow-lg">
            <div className="text-cyan-300 text-3xl font-mono font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-yellow-300 text-xl text-center px-4 font-mono">1st Term: {title}</span>
          </div>
        )}
      </div>
      
      {/* Right side: Term and definition */}
      <div className="relative z-10 w-1/2 pl-12">
        {title && (
          <h3 className="text-6xl font-mono text-yellow-300 mb-6 -rotate-1">{title}</h3>
        )}
        <div className="h-[3px] w-32 bg-green-400 mb-6 -rotate-1"></div>
        {content && (
          <div className="bg-[#2a2a2a]/80 border-l-4 border-green-400 p-6 rounded-r-lg shadow-lg">
            <p className="text-4xl font-mono leading-relaxed text-gray-200">{content}</p>
          </div>
        )}
      </div>
    </section>
  );
}

/* End Slide – Big thanks in chalk */
export function EndSlide() {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#1b1b1b] text-white flex flex-col items-center justify-center">
      <div className="absolute inset-10 border-[6px] border-pink-400/60 rounded-xl opacity-60"></div>
      <h2 className="text-8xl font-mono text-green-300 drop-shadow-lg">Thank You!</h2>
    </section>
  );
}

// Keep old component for backward compatibility
export function TOCSlideChalkboard({ title = "Table of Contents", items = [] }) {
  const tocData = {
    title,
    sections: items.map(item => ({ title: item, subsections: [] }))
  };
  return <TOCSlide tocData={tocData} />;
}

const DigitalChalkboard = {
  TitleSlide,
  TOCSlide,
  MainSlide1,
  MainSlide2,
  MainSlide3,
  ImageSlide,
  EndSlide,
};

export default DigitalChalkboard;
