import React from "react";
import { Landmark, Scroll, BookOpen, Feather, Hourglass } from "lucide-react";
import globe from "../imgs/globe.jpg";
import history from "../imgs/history.jpg";
import STILogo1 from "../STI LOGOS/STI LOGO1.png";

/* Title Slide – Split diagonal gold panel */
export function TitleSlide({ title, subtitle }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-yellow-900 text-yellow-100 overflow-hidden flex items-center justify-center">
      <img
        src={STILogo1}
        alt="STI LOGO1"
        className="absolute top-8 right-8 w-40 h-auto pointer-events-none select-none z-50"
      />
      {/* Diagonal golden panel */}
      <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-yellow-600 to-yellow-400 transform -skew-y-6 origin-top-left"></div>

      {/* Text */}
      <div className="relative z-10 text-center">
        <h1 className="text-7xl font-serif font-bold drop-shadow mb-4">{title}</h1>
        <h2 className="text-2xl italic font-serif">{subtitle}</h2>
      </div>
    </section>
  );
}


export function TOCSlide({ tocData }) {
  // Handle both old format (items array) and new format (tocData object)
  const title = tocData?.title || "Table of Contents";
  const sections = tocData?.sections || [];
  
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#fdfaf3] text-[#2b2b2b] flex flex-col items-center justify-center overflow-hidden">
      {/* Parchment texture overlay */}
      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/aged-paper.png')] opacity-50"></div>

      {/* Ornamental border */}
      <div className="absolute inset-16 border-[8px] border-[#8b5e3c] rounded-xl shadow-lg"></div>

      {/* Classical icons */}
      <div className="absolute top-24 left-24 text-7xl text-[#8b5e3c]/40">🏛️</div>
      <div className="absolute bottom-24 right-24 text-7xl text-[#b08d57]/40">📜</div>

      {/* Title */}
      <h2 className="text-6xl font-serif font-bold text-[#5a3d2b] mb-16 drop-shadow-lg">
        {title}
      </h2>

      {/* Two-Column Layout for TOC - Minimized to show only main sections */}
      <div className="grid grid-cols-2 gap-20 z-10 max-w-6xl w-full">
        {/* Left Column */}
        <div className="space-y-10">
          {sections.slice(0, Math.ceil(sections.length / 2)).map((section, sectionIndex) => (
            <div key={sectionIndex} className="flex items-center gap-8 hover:text-[#8b5e3c] transition-colors duration-300 group">
              <span className="w-20 h-20 flex items-center justify-center rounded-full bg-gradient-to-br from-[#d4af37] to-[#a67c00] group-hover:from-[#e6c547] group-hover:to-[#b8860b] text-white font-bold text-2xl shadow-lg border-3 border-amber-200 group-hover:border-amber-300 flex-shrink-0 transition-all duration-300">
                {sectionIndex + 1}
              </span>
              <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div className="space-y-10">
          {sections.slice(Math.ceil(sections.length / 2)).map((section, sectionIndex) => {
            const actualIndex = Math.ceil(sections.length / 2) + sectionIndex;
            return (
              <div key={actualIndex} className="flex items-center gap-8 hover:text-[#8b5e3c] transition-colors duration-300 group">
                <span className="w-20 h-20 flex items-center justify-center rounded-full bg-gradient-to-br from-[#d4af37] to-[#a67c00] group-hover:from-[#e6c547] group-hover:to-[#b8860b] text-white font-bold text-2xl shadow-lg border-3 border-amber-200 group-hover:border-amber-300 flex-shrink-0 transition-all duration-300">
                  {actualIndex + 1}
                </span>
                <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ---------------- MAIN SLIDE 1 ---------------- */
export function MainSlide1({ title, content, imageUrl, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-[#f5f1e8] to-[#e8dcc6] text-[#5a3d2b] flex items-center justify-between px-16 overflow-hidden">
      {/* Decorative elements */}
      <div className="absolute top-20 left-20 w-40 h-40 rounded-full bg-gradient-to-br from-[#d4af37]/30 to-[#a67c00]/30 blur-2xl"></div>
      <div className="absolute bottom-20 right-20 w-56 h-56 rounded-full bg-gradient-to-br from-[#b08d57]/30 to-[#8b5e3c]/30 blur-2xl"></div>

      {/* Left side: Auto-generated image placeholder for 2nd term */}
      <div className="relative z-10 w-1/2 h-full flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain rounded-lg shadow-2xl border-8 border-[#d4af37]" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-[#f9f6f0]/90 backdrop-blur-sm border-8 border-[#d4af37] rounded-2xl flex flex-col items-center justify-center shadow-2xl">
            <div className="text-[#5a3d2b] text-3xl font-serif font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-[#8b5e3c] text-xl text-center px-4 font-serif">2nd Term: {title}</span>
          </div>
        )}
      </div>

      {/* Right side: Term and definition */}
      <div className="relative z-10 w-1/2 pl-12">
        <div className="bg-[#f9f6f0]/90 backdrop-blur-sm border-4 border-[#d4af37] rounded-2xl p-8 shadow-2xl">
          <h2 className="text-6xl font-serif font-bold mb-6 text-[#5a3d2b]">{title}</h2>
          <div className="h-[4px] w-48 bg-gradient-to-r from-[#d4af37] to-[#a67c00] mb-6"></div>
          {content && (
            <div className="bg-gradient-to-br from-yellow-50/80 to-yellow-100/80 border-l-4 border-[#d4af37] p-6 rounded-r-lg">
              <p className="text-4xl leading-relaxed text-[#8b5e3c] font-serif">{content}</p>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}

// Keep old component for backward compatibility
export function TOCSlideHistoryHeritage({ title = "Table of Contents", items = [] }) {
  const tocData = {
    title,
    sections: items.map(item => ({ title: item, subsections: [] }))
  };
  return <TOCSlide tocData={tocData} />;
}

const HistoryHeritage = {
  TitleSlide,
  TOCSlide,
  MainSlide1,
  MainSlide2,
  MainSlide3,
  EndSlide,
};

export default HistoryHeritage;

/* Main Slide 2 – Framed parchment with top banner */
export function MainSlide2({ title, content, title2, content2 }) {
  return (
    <section
      className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-[#fdfaf4] to-[#f2e6ce] text-[#2b2118] flex flex-col items-center justify-center overflow-hidden"
      style={{
        fontFamily: "'Lora', serif",
      }}
    >
      {/* Background pattern */}
      <div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(191,161,106,0.05)_1px,transparent_1px),linear-gradient(45deg,rgba(191,161,106,0.05)_1px,transparent_1px)] bg-[size:60px_60px]"></div>

      {/* Top and bottom dividers */}
      <div className="absolute top-16 left-0 w-full h-[3px] bg-gradient-to-r from-transparent via-[#bfa06a] to-transparent"></div>
      <div className="absolute bottom-16 left-0 w-full h-[3px] bg-gradient-to-r from-transparent via-[#bfa06a] to-transparent"></div>

      {/* Top Half: First Term */}
      <div className="absolute top-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full bg-[#f9f6f0]/90 backdrop-blur-sm border-8 border-[#d4af37] rounded-2xl shadow-2xl p-8 flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-bold mb-4 text-[#5a3d2b]">{title || 'Term 1'}</h2>
          <div className="h-[4px] w-48 bg-gradient-to-r from-[#d4af37] to-[#a67c00] mb-4"></div>
          <p className="text-[2.5rem] leading-relaxed text-[#8b5e3c] font-serif">{content || 'Definition for term 1'}</p>
        </div>
      </div>

      {/* Bottom Half: Second Term */}
      <div className="absolute bottom-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full bg-[#f9f6f0]/90 backdrop-blur-sm border-8 border-[#b08d57] rounded-2xl shadow-2xl p-8 flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-bold mb-4 text-[#5a3d2b]">{title2 || 'Term 2'}</h2>
          <div className="h-[4px] w-48 bg-gradient-to-r from-[#b08d57] to-[#8b5e3c] mb-4"></div>
          <p className="text-[2.5rem] leading-relaxed text-[#8b5e3c] font-serif">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>
    </section>
  );
}

/* Main Slide 3 – Diagonal cut layout with golden overlay */
export function MainSlide3({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex text-yellow-50 overflow-hidden font-serif">
      {/* Vintage parchment texture background */}
      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/paper-fibers.png')] bg-repeat bg-[#f5deb3]"></div>

      {/* Soft vignette overlay */}
      <div className="absolute inset-0 bg-gradient-to-br from-[#7b5e2b]/40 via-[#a67c52]/20 to-transparent"></div>

      {/* Left image section */}
      <div className="w-2/5 h-full relative">
        <img
          src={globe}
          alt="Historical imagery"
          className="w-full h-full object-cover brightness-90 contrast-90"
        />
        {/* Sepia overlay for vintage tone */}
        <div className="absolute inset-0 bg-[#5c3d1e]/40 mix-blend-multiply"></div>
      </div>

      {/* Right text content */}
      <div className="flex-1 flex flex-col justify-center px-24 relative z-10">
        {/* Title */}
        <h2 className="text-7xl font-bold text-[#3b2f1c] mb-10 border-b-[3px] border-[#8b6b3b] pb-4 w-fit">
          {title}
        </h2>

        {/* Content */}
        <p className="text-[2.7rem] leading-relaxed text-[#4b3a21] max-w-3xl">
          {content}
        </p>
      </div>

      {/* Decorative gold line accents */}
      <div className="absolute top-10 left-0 w-full h-[4px] bg-gradient-to-r from-[#a87b4a] via-[#c9a66b] to-transparent opacity-70"></div>
      <div className="absolute bottom-10 right-0 w-full h-[4px] bg-gradient-to-l from-[#a87b4a] via-[#c9a66b] to-transparent opacity-70"></div>
    </section>
  );
}


/* Main Slide 4 – Scroll layout (ancient scroll effect) */
export function MainSlide4({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-b from-yellow-200 to-yellow-50 flex items-center justify-center text-gray-900 overflow-hidden">

      {/* Subtle background icons */}
      <Landmark className="absolute top-20 left-28 w-32 h-32 text-yellow-600 opacity-25 rotate-6" />
      <Scroll className="absolute bottom-24 right-32 w-28 h-28 text-amber-500 opacity-25 rotate-[-8deg]" />
      <BookOpen className="absolute top-1/3 right-1/4 w-28 h-28 text-orange-400 opacity-25" />
      <Feather className="absolute bottom-1/3 left-1/4 w-24 h-24 text-red-400 opacity-25" />
      <Hourglass className="absolute top-1/2 right-16 w-28 h-28 text-emerald-500 opacity-25 rotate-3" />

      {/* Decorative border */}
      <div className="absolute inset-12 border-4 border-amber-600 rounded-lg opacity-30" />

      {/* Left: First Term */}
      <div className="absolute left-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="bg-gradient-to-br from-yellow-50 to-yellow-100 border-8 border-yellow-700 rounded-xl shadow-2xl p-10">
          <h2 className="text-6xl font-serif font-bold text-yellow-900 mb-6">{title || 'Term 1'}</h2>
          <div className="h-[4px] w-40 bg-gradient-to-r from-yellow-600 to-yellow-800 mb-6"></div>
          <p className="text-[2.5rem] font-serif leading-relaxed text-yellow-900">{content || 'Definition for term 1'}</p>
        </div>
      </div>

      {/* Right: Second Term */}
      <div className="absolute right-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="bg-gradient-to-br from-yellow-50 to-yellow-100 border-8 border-amber-600 rounded-xl shadow-2xl p-10">
          <h2 className="text-6xl font-serif font-bold text-yellow-900 mb-6">{title2 || 'Term 2'}</h2>
          <div className="h-[4px] w-40 bg-gradient-to-r from-amber-600 to-amber-800 mb-6"></div>
          <p className="text-[2.5rem] font-serif leading-relaxed text-yellow-900">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>

    </section>
  );
}

export function MainSlide5({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex bg-[#f3e9d2] text-[#3b2f1c] font-serif overflow-hidden">
      {/* Parchment texture background */}
      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/paper-fibers.png')] opacity-80"></div>

      {/* Left text section */}
      <div className="flex-1 flex flex-col justify-center items-center text-center px-24 relative z-10">
        {/* Background icons (subtle historical vibe) */}
        <Landmark className="absolute top-24 left-28 w-32 h-32 text-[#85643b] opacity-20 rotate-6" />
        <Scroll className="absolute bottom-24 right-32 w-28 h-28 text-[#b48a5a] opacity-20 rotate-[-8deg]" />
        <BookOpen className="absolute top-1/3 right-1/4 w-28 h-28 text-[#9e7c4c] opacity-20" />
        <Feather className="absolute bottom-1/3 left-1/4 w-24 h-24 text-[#8b6b3b] opacity-20" />
        <Hourglass className="absolute top-1/2 right-16 w-28 h-28 text-[#d4af37] opacity-20 rotate-3" />

        {/* Decorative frame */}
        <div className="absolute inset-12 border-[3px] border-[#b5925a] rounded-lg opacity-30"></div>

        {/* Title */}
        <h2 className="text-7xl font-bold text-[#2b1e0f] mb-10 border-b-[3px] border-[#a67c52] pb-4 w-fit">
          {title}
        </h2>

        {/* Content */}
        <p className="max-w-4xl text-[2.7rem] leading-relaxed text-[#4a3722]">
          {content}
        </p>
      </div>

      {/* Right image section */}
      <div className="w-2/5 h-full relative">
        <img
          src={history}
          alt="Historical architecture"
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-[#5c3a1e]/50 mix-blend-multiply"></div>
      </div>

      {/* Top and bottom gold dividers */}
      <div className="absolute top-10 left-0 w-full h-[4px] bg-gradient-to-r from-[#c9a66b] via-[#b68c47] to-transparent opacity-70"></div>
      <div className="absolute bottom-10 right-0 w-full h-[4px] bg-gradient-to-l from-[#c9a66b] via-[#b68c47] to-transparent opacity-70"></div>
    </section>
  );
}


/* Main Slide 6 – Golden arch motif */
export function MainSlide6({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-yellow-900 via-yellow-800 to-yellow-600 text-yellow-100 flex items-center justify-center overflow-hidden">
      {/* Arch frame */}
      <div className="absolute inset-0 flex items-center justify-center">
        <div className="w-[1200px] h-[800px] border-[16px] border-yellow-400/70 rounded-t-full rounded-b-lg opacity-40"></div>
      </div>

      {/* Inner glow arch */}
      <div className="absolute inset-0 flex items-center justify-center">
        <div className="w-[1000px] h-[650px] border-[10px] border-yellow-300/50 rounded-t-full rounded-b-lg opacity-50"></div>
      </div>

      {/* Content inside the arch */}
      <div className="relative z-10 text-center max-w-5xl">
        <h2 className="text-7xl font-serif font-bold mb-8">{title}</h2>
        <p className="text-[2.5rem] font-serif leading-relaxed">{content}</p>
      </div>
    </section>
  );
}



/* Image Slide – Gold pedestal frame */
export function ImageSlide({ title, content, imageUrl, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-b from-yellow-100 to-yellow-50 flex items-center justify-between px-16">
      {/* Frame */}
      <div className="absolute inset-10 border-[10px] border-yellow-700 rounded-xl"></div>
      
      {/* Left side: Auto-generated image placeholder for 1st term */}
      <div className="relative z-10 w-1/2 h-full flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain rounded-lg shadow-2xl border-8 border-yellow-600" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-gradient-to-br from-yellow-50 to-yellow-100 border-8 border-yellow-700 rounded-xl flex flex-col items-center justify-center shadow-2xl">
            <div className="text-yellow-800 text-3xl font-serif font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-yellow-700 text-xl text-center px-4 font-serif">1st Term: {title}</span>
          </div>
        )}
      </div>
      
      {/* Right side: Term and definition */}
      <div className="relative z-10 w-1/2 pl-12">
        {title && (
          <h3 className="text-6xl font-serif font-bold text-yellow-900 mb-6">{title}</h3>
        )}
        <div className="h-[4px] w-40 bg-gradient-to-r from-yellow-600 to-yellow-800 mb-6"></div>
        {content && (
          <div className="bg-gradient-to-br from-yellow-50/90 to-yellow-100/90 border-l-8 border-yellow-700 p-6 rounded-r-xl shadow-xl backdrop-blur-sm">
            <p className="text-4xl leading-relaxed text-yellow-900 font-serif">{content}</p>
          </div>
        )}
      </div>
    </section>
  );
}

/* End Slide – Strong regal close with diagonal overlay */
export function EndSlide({ message }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex items-center justify-center text-yellow-100 overflow-hidden">
      {/* Gold gradient */}
      <div className="absolute inset-0 bg-gradient-to-r from-yellow-900 via-yellow-800 to-yellow-600"></div>
      {/* Diagonal overlay */}
      <div className="absolute inset-0 bg-gradient-to-tr from-yellow-700/50 to-yellow-500/30 transform skew-y-3"></div>

      {/* Subtle background icons */}
      <Landmark className="absolute top-24 left-24 w-32 h-32 text-yellow-600 opacity-25" />
      <Scroll className="absolute bottom-28 right-28 w-28 h-28 text-amber-500 opacity-25" />
      <BookOpen className="absolute top-1/3 left-1/4 w-28 h-28 text-orange-400 opacity-25" />
      <Feather className="absolute bottom-1/3 right-1/4 w-24 h-24 text-red-400 opacity-25" />
      <Hourglass className="absolute top-1/2 right-16 w-28 h-28 text-emerald-500 opacity-25" />

      <div className="relative z-10 text-center">
        <h2 className="text-6xl font-serif font-bold mb-4">{message}</h2>
        <p className="text-8xl italic">Thank You</p>
      </div>
    </section>
  );
}


