import React from "react";
import research from '../imgs/research.jpg';
import STILogo1 from "../STI LOGOS/STI LOGO1.png";

/* ---------------- TITLE SLIDE ---------------- */
export function TitleSlide({ title, subtitle }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-white flex flex-col items-center justify-center text-center px-16">
      <img
        src={STILogo1}
        alt="STI LOGO1"
        className="absolute top-8 right-8 w-40 h-auto pointer-events-none select-none"
      />
      {/* Top accent bar */}
      <div className="absolute top-0 w-full h-6 bg-blue-900"></div>

      <h1 className="text-6xl font-serif font-bold text-gray-900 mb-4">
        {title}
      </h1>
      <h2 className="text-2xl font-sans font-light text-gray-700">
        {subtitle}
      </h2>

      {/* Bottom bar */}
      <div className="absolute bottom-0 w-full h-4 bg-gray-200"></div>
    </section>
  );
}

export function TOCSlide({ tocData }) {
  // Handle both old format (items array) and new format (tocData object)
  const title = tocData?.title || "Table of Contents";
  const sections = tocData?.sections || [];
  
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-[#f7f9fc] to-[#e6ecf5] text-[#1c1c1c] flex flex-col items-center justify-center overflow-hidden">
      {/* Subtle grid / notebook lines */}
      <div className="absolute inset-0 opacity-30 bg-[linear-gradient(to_right,rgba(0,0,0,0.05)_1px,transparent_1px),linear-gradient(to_bottom,rgba(0,0,0,0.05)_1px,transparent_1px)] bg-[size:80px_80px]"></div>

      {/* Accent shapes */}
      <div className="absolute top-16 left-24 w-24 h-24 rounded-full bg-blue-500/20"></div>
      <div className="absolute bottom-24 right-36 w-32 h-32 rounded-lg bg-indigo-400/20 rotate-12"></div>

      {/* Title */}
      <h2 className="text-6xl font-bold text-[#1e3a8a] mb-16 drop-shadow-sm tracking-wide">
        {title}
      </h2>

      {/* Two-Column Layout for TOC - Minimized to show only main sections */}
      <div className="grid grid-cols-2 gap-20 z-10 max-w-6xl w-full">
        {/* Left Column */}
        <div className="space-y-10">
          {sections.slice(0, Math.ceil(sections.length / 2)).map((section, sectionIndex) => (
            <div key={sectionIndex} className="flex items-center gap-8 hover:text-blue-600 transition-colors duration-300 group">
              <span className="w-20 h-20 flex items-center justify-center rounded-full bg-blue-500 group-hover:bg-blue-600 text-white text-2xl font-bold flex-shrink-0 border-3 border-blue-200 group-hover:border-blue-300 transition-all duration-300 shadow-lg">
                {sectionIndex + 1}
              </span>
              <span className="flex-1 text-left leading-tight font-semibold text-5xl group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div className="space-y-10">
          {sections.slice(Math.ceil(sections.length / 2)).map((section, sectionIndex) => {
            const actualIndex = Math.ceil(sections.length / 2) + sectionIndex;
            return (
              <div key={actualIndex} className="flex items-center gap-8 hover:text-blue-600 transition-colors duration-300 group">
                <span className="w-20 h-20 flex items-center justify-center rounded-full bg-blue-500 group-hover:bg-blue-600 text-white text-2xl font-bold flex-shrink-0 border-3 border-blue-200 group-hover:border-blue-300 transition-all duration-300 shadow-lg">
                  {actualIndex + 1}
                </span>
                <span className="flex-1 text-left leading-tight font-semibold text-5xl group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ---------------- MAIN SLIDE 1 ---------------- */
export function MainSlide1({ title, content, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-white flex px-20 py-16">
      {/* Left: auto image or placeholder for 2nd term */}
      <div className="w-1/2 h-full pr-10 flex items-center justify-center">
        {autoGeneratedImage ? (
          <img
            src={autoGeneratedImage}
            alt={title}
            className="w-[760px] h-[540px] object-cover rounded-md border-4 border-blue-700/60 shadow-xl"
          />
        ) : (
          <div className="w-[760px] h-[540px] bg-gray-50 border-4 border-blue-300/80 rounded-md flex flex-col items-center justify-center">
            <div className="text-blue-800 text-2xl font-serif font-bold mb-3">Auto Image Placeholder</div>
            <span className="text-blue-700 text-xl font-sans">2nd Term MainSlide</span>
          </div>
        )}
      </div>

      {/* Right: title and content */}
      <div className="w-1/2 flex flex-col">
        <h2 className="text-7xl font-serif font-bold text-blue-900 mb-2">
          {title}
        </h2>
        <div className="h-[3px] w-24 bg-blue-700 mb-6"></div>
        <p className="text-[2.6rem] font-sans text-gray-800 leading-relaxed">
          {content}
        </p>
      </div>
    </section>
  );
}

/* ---------------- MAIN SLIDE 2 ---------------- */
export function MainSlide2({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-gray-100 to-gray-200 flex flex-col items-center justify-center px-32 py-20 overflow-hidden">
      {/* Abstract geometric shapes for subtle academic texture */}
      <div className="absolute top-24 left-16 w-64 h-64 bg-blue-100 rounded-full opacity-30 blur-3xl"></div>
      <div className="absolute bottom-16 right-20 w-72 h-72 bg-indigo-200 rounded-full opacity-25 blur-3xl"></div>

      {/* Top Half: First Term */}
      <div className="absolute top-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full bg-white border border-gray-200 shadow-lg rounded-lg p-8 flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-semibold text-blue-900 mb-4">{title || 'Term 1'}</h2>
          <div className="h-[4px] w-32 bg-blue-700 mb-6 rounded"></div>
          <p className="text-[2.5rem] font-sans text-gray-800 leading-relaxed">{content || 'Definition for term 1'}</p>
        </div>
      </div>

      {/* Bottom Half: Second Term */}
      <div className="absolute bottom-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full bg-white border border-gray-200 shadow-lg rounded-lg p-8 flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-semibold text-indigo-900 mb-4">{title2 || 'Term 2'}</h2>
          <div className="h-[4px] w-32 bg-indigo-700 mb-6 rounded"></div>
          <p className="text-[2.5rem] font-sans text-gray-800 leading-relaxed">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>
    </section>
  );
}


/* ---------------- MAIN SLIDE 3 ---------------- */
export function MainSlide3({ title, content, image }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex items-center justify-between overflow-hidden bg-gradient-to-br from-blue-50 via-white to-gray-100 px-32">
      {/* Background atmosphere */}
      <div className="absolute -left-32 top-0 w-[700px] h-[700px] bg-blue-300/30 rounded-full blur-3xl"></div>
      <div className="absolute top-40 right-0 w-[600px] h-[600px] bg-purple-300/20 rounded-full blur-2xl"></div>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(30,64,175,0.05),transparent_60%)]"></div>
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#1e3a8a_1px,transparent_1px),linear-gradient(to_bottom,#1e3a8a_1px,transparent_1px)] bg-[size:90px_90px] opacity-10"></div>

      {/* Left accent strip */}
      <div className="absolute left-0 top-0 h-full w-12 bg-gradient-to-b from-blue-900 to-blue-600 shadow-2xl"></div>

      {/* Text content */}
      <div className="relative z-10 max-w-4xl ml-24">
        <h2 className="text-7xl font-serif font-bold text-blue-950 mb-8 drop-shadow-[0_0_20px_rgba(59,130,246,0.3)]">
          {title}
        </h2>
        <p className="text-[2.7rem] font-sans text-gray-800 leading-relaxed">
          {content}
        </p>
      </div>

      {/* Right-side image glass panel */}
      <div className="relative w-[30%] h-[80%] mr-24 rounded-3xl overflow-hidden shadow-2xl bg-gradient-to-br from-blue-200/40 to-purple-200/30 backdrop-blur-md border border-blue-300/30">
        <img
            src={research}
            alt="Research visual"
            className="absolute inset-0 w-full h-full object-cover mix-blend-overlay"
          />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(255,255,255,0.15),transparent_70%)]"></div>
      </div>
    </section>
  );
}


/* ---------------- MAIN SLIDE 4 ---------------- */
export function MainSlide4({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-r from-gray-50 to-white flex items-center justify-center px-24 py-16">
      {/* Left: First Term */}
      <div className="absolute left-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="bg-white border border-gray-200 shadow-lg rounded-lg p-10">
          <h2 className="text-6xl font-serif font-bold text-blue-900 mb-4">{title || 'Term 1'}</h2>
          <div className="h-[4px] w-32 bg-blue-700 mb-6 rounded"></div>
          <p className="text-[2.5rem] font-sans text-gray-800 leading-relaxed">{content || 'Definition for term 1'}</p>
        </div>
      </div>

      {/* Right: Second Term */}
      <div className="absolute right-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="bg-white border border-gray-200 shadow-lg rounded-lg p-10">
          <h2 className="text-6xl font-serif font-bold text-indigo-900 mb-4">{title2 || 'Term 2'}</h2>
          <div className="h-[4px] w-32 bg-indigo-700 mb-6 rounded"></div>
          <p className="text-[2.5rem] font-sans text-gray-800 leading-relaxed">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>
    </section>
  );
}

/* ---------------- MAIN SLIDE 5 ---------------- */
export function MainSlide5({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-white via-slate-50 to-slate-100 flex px-24 py-16">
      {/* Left accent bar */}
      <div className="w-6 bg-blue-900 rounded-full"></div>

      {/* Main content */}
      <div className="flex-1 flex flex-col justify-center pl-16">
        <h2 className="text-7xl font-serif font-semibold text-gray-900 mb-8 tracking-tight">
          {title}
        </h2>

        <div className="border-l-4 border-blue-800 pl-6">
          <p className="text-[2.7rem] font-sans text-gray-800 leading-relaxed max-w-4xl">
            {content}
          </p>
        </div>
      </div>
    </section>
  );
}

/* ---------------- MAIN SLIDE 6 ---------------- */
export function MainSlide6({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] overflow-hidden flex flex-col justify-center px-32 bg-gradient-to-br from-blue-950 via-slate-900 to-indigo-950 text-white">
      {/* Layered abstract gradient glow */}
      <div className="absolute top-0 left-0 w-[600px] h-[600px] bg-blue-500/30 blur-3xl rounded-full"></div>
      <div className="absolute bottom-0 right-0 w-[700px] h-[700px] bg-cyan-400/20 blur-3xl rounded-full"></div>

      {/* Diagonal accent layer */}
      <div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(255,255,255,0.05)_25%,transparent_25%,transparent_50%,rgba(255,255,255,0.05)_50%,rgba(255,255,255,0.05)_75%,transparent_75%,transparent)] bg-[size:100px_100px] opacity-20"></div>

      {/* Futuristic horizontal lines */}
      <div className="absolute top-1/3 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-blue-400/40 to-transparent"></div>
      <div className="absolute top-2/3 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-cyan-400/40 to-transparent"></div>

      {/* Header */}
      <div className="relative z-10 mb-12">
        <h2 className="text-7xl font-serif font-bold tracking-tight mb-4">
          {title}
        </h2>
        <div className="h-[5px] w-40 bg-gradient-to-r from-cyan-400 to-blue-600 rounded-full"></div>
      </div>

      {/* Content */}
      <div className="relative z-10 max-w-6xl">
        <p className="text-[2.7rem] leading-relaxed text-gray-100 font-light">
          {content}
        </p>
      </div>

      {/* Abstract floating shapes */}
      <div className="absolute bottom-24 left-1/2 -translate-x-1/2 flex space-x-16 opacity-40">
        <div className="w-32 h-32 border border-cyan-400/50 rotate-45"></div>
        <div className="w-16 h-16 border border-blue-400/50 rounded-full"></div>
        <div className="w-24 h-24 border border-indigo-400/50 rotate-12"></div>
      </div>
    </section>
  );
}



/* ---------------- IMAGE SLIDE ---------------- */
export function ImageSlide({ title, content, autoGeneratedImage, imageUrl }) {
  const imageSrc = autoGeneratedImage || imageUrl;
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gray-50 flex items-center justify-center px-16">
      <div className="relative z-10 w-full h-5/6 flex items-center justify-between">
        {/* Left: auto image or placeholder for 1st term */}
        <div className="w-1/2 h-full flex items-center justify-center pr-10">
          {imageSrc ? (
            <img
              src={imageSrc}
              alt={title}
              className="max-w-full max-h-full object-contain rounded-md border-4 border-blue-700/60 shadow-xl bg-white"
            />
          ) : (
            <div className="w-[800px] h-[480px] bg-white border-4 border-blue-300/80 rounded-md flex flex-col items-center justify-center">
              <div className="text-blue-800 text-2xl font-serif font-bold mb-3">Auto Image Placeholder</div>
              <span className="text-blue-700 text-xl font-sans">1st Term ImageSlide</span>
            </div>
          )}
        </div>

        {/* Right: title and definition */}
        <div className="w-1/2 text-[#1c1c1c] pl-8">
          {title && (
            <h2 className="text-6xl font-serif font-bold text-blue-900 mb-6">
              {title}
            </h2>
          )}
          {content && <p className="text-4xl font-sans text-gray-800 leading-relaxed">{content}</p>}
        </div>
      </div>
    </section>
  );
}

/* ---------------- END SLIDE ---------------- */
export function EndSlide() {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-blue-900 flex items-center justify-center">
      <h1 className="text-4xl font-serif font-bold text-white">Thank You</h1>
    </section>
  );
}

// Keep old component for backward compatibility
export function TOCSlideResearchReady({ title = "Table of Contents", items = [] }) {
  const tocData = {
    title,
    sections: items.map(item => ({ title: item, subsections: [] }))
  };
  return <TOCSlide tocData={tocData} />;
}

const ResearchReady = {
  TitleSlide,
  TOCSlide,
  MainSlide1,
  MainSlide2,
  MainSlide3,
  MainSlide4,
  MainSlide5,
  MainSlide6,
  ImageSlide,
  EndSlide,
};
export default ResearchReady;
