import React from "react";
import { BookOpen, Scroll, PenTool, GraduationCap } from "lucide-react";
import writing from "../imgs/writing.jpg";
import manybooks from "../imgs/manybooks.jpg";
import STILogo1 from "../STI LOGOS/STI LOGO1.png";

/* Title Slide – Split with vertical divider */
export function TitleSlide({ title, subtitle }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-gray-100 to-gray-200 flex items-center px-24">
      <img
        src={STILogo1}
        alt="STI LOGO1"
        className="absolute top-8 right-8 w-40 h-auto pointer-events-none select-none"
      />
      <div className="flex-1 pr-12">
        <h1 className="text-6xl font-serif font-bold text-gray-900 mb-6">{title}</h1>
        <h2 className="text-2xl font-serif italic text-gray-700">{subtitle}</h2>
      </div>
      <div className="w-[3px] h-64 bg-yellow-600"></div>
      <div className="flex-1 pl-12 flex items-center justify-center">
        <div className="w-64 h-64 border-4 border-yellow-600 rounded-full opacity-20"></div>
      </div>
    </section>
  );
}

/* Table of Contents Slide – Scholarly Elegant */
export function TOCSlide({ tocData }) {
  // Handle both old format (items array) and new format (tocData object)
  const title = tocData?.title || "Table of Contents";
  const sections = tocData?.sections || [];
  
  return (
    <section className="relative w-[1920px] h-[1080px] bg-[#0e1a2a] text-white flex flex-col items-center justify-center overflow-hidden">
      {/* Elegant border frame */}
      <div className="absolute inset-16 border-4 border-yellow-600/70 rounded-lg"></div>

      {/* Title */}
      <h2 className="text-5xl font-serif font-bold text-yellow-400 mb-20 tracking-wide">
        {title}
      </h2>

      {/* Two-Column Layout for TOC - Simplified to show only main sections */}
      <div className="grid grid-cols-2 gap-20 z-10 max-w-6xl w-full">
        {/* Left Column */}
        <div className="space-y-10">
          {sections.slice(0, Math.ceil(sections.length / 2)).map((section, sectionIndex) => (
            <div key={sectionIndex} className="flex items-center gap-8 text-gray-200 hover:text-yellow-300 transition-colors duration-300 group">
              <div className="w-20 h-20 flex items-center justify-center rounded-full border-3 border-yellow-600 group-hover:border-yellow-500 bg-yellow-600/10 group-hover:bg-yellow-600/20 text-yellow-400 text-2xl font-bold flex-shrink-0 transition-all duration-300 shadow-lg">
                {sectionIndex + 1}
              </div>
              <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div className="space-y-10">
          {sections.slice(Math.ceil(sections.length / 2)).map((section, sectionIndex) => {
            const actualIndex = Math.ceil(sections.length / 2) + sectionIndex;
            return (
              <div key={actualIndex} className="flex items-center gap-8 text-gray-200 hover:text-yellow-300 transition-colors duration-300 group">
                <div className="w-20 h-20 flex items-center justify-center rounded-full border-3 border-yellow-600 group-hover:border-yellow-500 bg-yellow-600/10 group-hover:bg-yellow-600/20 text-yellow-400 text-2xl font-bold flex-shrink-0 transition-all duration-300 shadow-lg">
                  {actualIndex + 1}
                </div>
                <span className="text-5xl font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}


/* Main Slide 1 – Title on top, underline, content below */
export function MainSlide1({ title, content, imageUrl, autoGeneratedImage }) {
  return (
    <section className="w-[1920px] h-[1080px] bg-white text-gray-900 px-24 py-16 flex items-center justify-between">

      <div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_center,rgba(0,0,0,0.05),transparent_70%)]" />

      {/* Scholarly faded icons */}
      <Scroll className="absolute bottom-32 right-24 w-28 h-28 text-[#6e5a3d]/20" />
      <PenTool className="absolute top-1/3 right-1/4 w-24 h-24 text-[#4a3826]/20 rotate-[-15deg]" />
      <GraduationCap className="absolute bottom-20 left-1/4 w-28 h-28 text-[#5c4933]/20" />

      {/* Decorative border frame */}
      <div className="absolute inset-12 border-4 border-[#b9a07f] rounded-2xl opacity-40" />

      {/* Left side: Auto-generated image placeholder for 2nd term */}
      <div className="relative z-10 w-1/2 h-full flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain border-4 border-gray-700 rounded-lg shadow-xl" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-white border-4 border-gray-600 rounded-lg flex flex-col items-center justify-center shadow-xl">
            <div className="text-gray-700 text-3xl font-serif font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-gray-600 text-xl text-center px-4 font-serif">2nd Term: {title}</span>
          </div>
        )}
      </div>

      {/* Right side: Term and definition */}
      <div className="relative z-10 w-1/2 pl-12">
        <h2 className="text-7xl font-serif font-bold mb-4 text-gray-800">{title}</h2>
        <div className="h-[3px] w-40 bg-yellow-600 mb-8"></div>
        {content && (
          <div className="bg-gray-50/80 border-l-4 border-yellow-600 p-6 rounded-r-lg shadow-lg">
            <div className="text-[2.5rem] font-serif leading-relaxed text-gray-700">{content}</div>
          </div>
        )}
      </div>
    </section>
  );
}

/* Main Slide 2 – Two columns, left for title+content, right decorative */
export function MainSlide2({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gray-50 text-gray-900 px-20 py-16 flex flex-col items-center justify-center">

      <div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_center,rgba(0,0,0,0.05),transparent_70%)]" />

      {/* Scholarly faded icons */}
      <Scroll className="absolute bottom-32 right-24 w-28 h-28 text-[#6e5a3d]/20" />
      <PenTool className="absolute top-1/3 right-1/4 w-24 h-24 text-[#4a3826]/20 rotate-[-15deg]" />
      <GraduationCap className="absolute bottom-20 left-1/4 w-28 h-28 text-[#5c4933]/20" />

      {/* Decorative border frame */}
      <div className="absolute inset-12 border-4 border-[#b9a07f] rounded-2xl opacity-40" />

      {/* Top Half: First Term */}
      <div className="absolute top-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="bg-white border-4 border-yellow-600 rounded-lg shadow-2xl p-8 h-full flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-bold mb-4 text-gray-800">
            {title || 'Term 1'}
          </h2>
          <div className="h-[3px] w-40 bg-yellow-600 mb-4"></div>
          <div className="text-4xl font-serif leading-relaxed text-gray-700">
            {content || 'Definition for term 1'}
          </div>
        </div>
      </div>

      {/* Bottom Half: Second Term */}
      <div className="absolute bottom-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="bg-white border-4 border-yellow-600 rounded-lg shadow-2xl p-8 h-full flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-bold mb-4 text-gray-800">
            {title2 || 'Term 2'}
          </h2>
          <div className="h-[3px] w-40 bg-yellow-600 mb-4"></div>
          <div className="text-4xl font-serif leading-relaxed text-gray-700">
            {content2 || 'Definition for term 2'}
          </div>
        </div>
      </div>
    </section>
  );
}

/* Main Slide 3 – Full border frame with content centered */
export function MainSlide3({ title, content, image }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex bg-[#f9f5f0] text-[#3b2f2f] overflow-hidden font-serif">
      {/* Left visual section */}
      <div className="w-1/2 h-full relative flex items-center justify-center">
        {/* Subtle warm overlay */}
        <div className="absolute inset-0 bg-gradient-to-b from-[#d9c2a7]/60 to-[#f9f5f0]/40 mix-blend-multiply"></div>

        <img
            src={writing}
            alt="Slide Visual"
            className="w-full h-full object-cover opacity-90"
          />
      </div>

      {/* Right content section */}
      <div className="w-1/2 h-full flex flex-col justify-center px-32 relative">
        {/* Large decorative text in background */}
        <h1 className="absolute top-[15%] left-[5%] text-[10rem] font-serif text-[#d8c8a6]/20 tracking-wider select-none uppercase">
          {title?.slice(0, 3) || "TXT"}
        </h1>

        {/* Title */}
        <h2 className="text-7xl font-serif font-bold mb-10 z-10 text-[#3b2f2f] leading-tight">
          <span className="text-[#b68d40]"></span>
          {title}
          <span className="text-[#b68d40]"></span>
        </h2>

        {/* Content */}
        <p className="text-[2.5rem] font-serif text-[#5a4a3c] leading-relaxed z-10 max-w-[85%]">
          {content}
        </p>

        {/* Gold accent line */}
        <div className="w-44 h-[3px] bg-gradient-to-r from-[#d4af37] to-[#b68d40] mt-16 rounded-full shadow-[0_0_10px_rgba(212,175,55,0.6)]"></div>

        {/* Decorative circle (subtle gold touch) */}
        <div className="absolute bottom-[10%] right-[10%] w-40 h-40 rounded-full border-[1px] border-[#d4af37]/50 blur-[0.5px]"></div>
      </div>
    </section>
  );
}


/* Image Slide – Left image, right caption */
export function ImageSlide({ title, content, imageUrl, autoGeneratedImage, caption }) {
  return (
    <section className="w-[1920px] h-[1080px] bg-gray-100 text-gray-900 px-20 py-12 flex items-center">
      {/* Left side: Auto-generated image placeholder for 1st term */}
      <div className="flex-1 flex items-center justify-center pr-12">
        {autoGeneratedImage ? (
          <img 
            src={autoGeneratedImage} 
            alt={title} 
            className="max-w-full max-h-full object-contain border-4 border-gray-700 rounded-lg shadow-xl" 
          />
        ) : (
          <div className="w-4/5 h-4/5 bg-white border-4 border-gray-600 rounded-lg flex flex-col items-center justify-center shadow-xl">
            <div className="text-gray-700 text-3xl font-serif font-bold mb-4">🎨 Auto Image Placeholder</div>
            <span className="text-gray-600 text-xl text-center px-4 font-serif">1st Term: {title}</span>
          </div>
        )}
      </div>
      
      <div className="w-[2px] h-[80%] bg-yellow-600"></div>
      
      {/* Right side: Term and definition */}
      <div className="flex-1 pl-12">
        {title && (
          <h3 className="text-6xl font-serif font-bold mb-6 text-gray-800">{title}</h3>
        )}
        <div className="h-[3px] w-32 bg-yellow-600 mb-6"></div>
        {content && (
          <div className="bg-white/80 border-l-4 border-yellow-600 p-6 rounded-r-lg shadow-lg">
            <p className="text-4xl font-serif leading-relaxed text-gray-700">{content}</p>
          </div>
        )}
      </div>
    </section>
  );
}

/* End Slide – Framed closing */
export function EndSlide({ message }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-gray-200 to-gray-100 flex flex-col items-center justify-center text-gray-900 overflow-hidden">

      <div className="absolute inset-16 border-8 border-[#b9a07f] rounded-xl opacity-50" />

      {/* Scholarly faded icons */}
      <BookOpen className="absolute top-24 left-24 w-28 h-28 text-[#5a4632]/20" />
      <Scroll className="absolute bottom-28 right-24 w-32 h-32 text-[#6e5a3d]/20" />
      <PenTool className="absolute top-1/2 right-1/4 w-24 h-24 text-[#4a3826]/20 rotate-12" />

      <div className="absolute inset-6 border-4 border-yellow-600 rounded-xl"></div>
      <h2 className="text-5xl font-serif font-bold mb-6">{message}</h2>
      <p className="text-8xl font-serif italic text-gray-700">Thank you</p>
    </section>
  );
}

/* Main Slide 4 – Horizontal split (title/content left, content right) */
export function MainSlide4({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-white text-gray-900 flex items-center justify-center overflow-hidden">
      {/* Decorative background */}
      <div className="absolute inset-0 bg-gradient-to-br from-gray-100 to-gray-200"></div>
      <div className="absolute top-20 left-20 w-40 h-40 bg-yellow-500/20 rounded-full blur-3xl"></div>

      {/* Left: First Term */}
      <div className="flex-1 px-24 py-20 z-10 flex flex-col justify-center h-[80%]">
        <div className="bg-white border-4 border-yellow-600 rounded-lg shadow-xl p-8 h-full flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-bold mb-6 text-gray-800">{title || 'Term 1'}</h2>
          <div className="h-[3px] w-32 bg-yellow-600 mb-4"></div>
          <p className="text-[2.5rem] font-serif leading-relaxed text-gray-700">{content || 'Definition for term 1'}</p>
        </div>
      </div>

      {/* Divider */}
      <div className="w-[3px] bg-yellow-600 opacity-70 my-24 h-[500px]"></div>

      {/* Right: Second Term */}
      <div className="flex-1 px-24 py-20 z-10 flex items-center h-[80%]">
        <div className="bg-white border-4 border-yellow-600 rounded-lg shadow-xl p-8 h-full flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-bold mb-6 text-gray-800">{title2 || 'Term 2'}</h2>
          <div className="h-[3px] w-32 bg-yellow-600 mb-4"></div>
          <p className="text-[2.5rem] font-serif leading-relaxed text-gray-700">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>
    </section>
  );
}

export function MainSlide6({ title, content, image }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex bg-[#f7f3ef] text-[#2e2a25] font-serif overflow-hidden">
      {/* Background subtle pattern */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#e9e4dc_1px,transparent_1px),linear-gradient(to_bottom,#e9e4dc_1px,transparent_1px)] bg-[size:40px_40px] opacity-30"></div>

      {/* Decorative corner shapes */}
      <div className="absolute top-10 left-10 w-[140px] h-[140px] border-[3px] border-[#bfa26f] rounded-md"></div>
      <div className="absolute bottom-10 left-10 w-[100px] h-[100px] bg-[#bfa26f]/20 -rotate-12"></div>

      {/* Left section - Content */}
      <div className="w-[70%] h-full flex flex-col justify-center px-28 relative">
        {/* Top and bottom gold borders */}
        <div className="absolute top-0 left-0 w-full h-[8px] bg-gradient-to-r from-[#bfa26f] via-[#e4d1a1] to-[#bfa26f]"></div>
        <div className="absolute bottom-0 left-0 w-full h-[8px] bg-gradient-to-r from-[#bfa26f] via-[#e4d1a1] to-[#bfa26f]"></div>

        {/* Large faded initial letter */}
        <span className="absolute text-[18rem] font-serif text-[#bfa26f]/10 top-[10%] right-[5%] select-none">
          {title?.[0] || "A"}
        </span>

        {/* Title */}
        <h2 className="text-7xl font-serif font-bold mb-10 leading-tight text-[#2e2a25] relative z-10">
          {title}
        </h2>

        {/* Content */}
        <p className="text-[2.7rem] font-serif leading-relaxed text-[#4b4035] z-10 max-w-[85%]">
          {content}
        </p>

        {/* Gold underline accent */}
        <div className="mt-12 w-[200px] h-[3px] bg-gradient-to-r from-[#bfa26f] to-[#e6d49c] shadow-[0_0_10px_rgba(191,162,111,0.5)]"></div>
      </div>

      {/* Right section - Image */}
      <div className="w-[30%] h-full relative flex items-center justify-center bg-[#e9e4dc] border-l-[6px] border-[#c6a85f]">
        <img
            src={manybooks}
            alt="Slide Visual"
            className="w-full h-full object-cover opacity-90"
          />
      </div>
    </section>
  );
}


// Keep old component for backward compatibility
export function TOCSlideScholarly({ title = "Table of Contents", items = [] }) {
  const tocData = {
    title,
    sections: items.map(item => ({ title: item, subsections: [] }))
  };
  return <TOCSlide tocData={tocData} />;
}

const ScholarlyElegant = {
  TitleSlide,
  TOCSlide,
  MainSlide1,
  MainSlide2,
  MainSlide3,
  ImageSlide,
  EndSlide,
};

export default ScholarlyElegant;
