import React from "react";
import { BookOpen, PenTool, GraduationCap, Scroll, Globe } from "lucide-react";
import STILogo1 from "../STI LOGOS/STI LOGO1.png";

/* ---------------- TITLE SLIDE ---------------- */
export function TitleSlide({ title, subtitle }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-green-900 to-emerald-700 flex flex-col items-center justify-center text-center">
      <img
        src={STILogo1}
        alt="STI LOGO1"
        className="absolute top-8 right-8 w-40 h-auto pointer-events-none select-none"
      />
      {/* Decorative underline with flourish */}
      <h1 className="text-7xl font-serif text-green-100 font-bold mb-4 drop-shadow-lg">
        {title}
      </h1>
      <div className="h-[4px] w-40 bg-green-400 rounded-full mb-4 shadow-[0_0_10px_rgba(34,197,94,0.7)]"></div>
      <h2 className="text-2xl font-light italic text-green-200">{subtitle}</h2>
    </section>
  );
}

/* ---------------- MAIN SLIDE 1 ---------------- */
/* Left-aligned title sidebar, wide content on right */
export function MainSlide1({ title, content, autoGeneratedImage }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-green-50 flex">
      {/* Left: auto image or placeholder for 2nd term */}
      <div className="w-1/2 h-full flex items-center justify-center p-12">
        {autoGeneratedImage ? (
          <img
            src={autoGeneratedImage}
            alt={title}
            className="w-full h-[540px] object-cover rounded-2xl border-[10px] border-green-600/70 shadow-2xl"
          />
        ) : (
          <div className="w-[820px] h-[540px] bg-white/80 border-[10px] border-green-500/70 rounded-2xl shadow-2xl flex flex-col items-center justify-center">
            <div className="text-green-800 text-3xl font-serif font-bold mb-4">Auto Image Placeholder</div>
            <span className="text-green-700 text-xl">2nd Term MainSlide</span>
          </div>
        )}
      </div>

      {/* Content side */}
      <div className="w-1/2 p-16 flex flex-col justify-center">
        <h2 className="text-6xl text-black font-bold border-b-2 border-green-500 pb-4 mb-6">
          {title}
        </h2>
        <p className="text-[2.7rem] text-black font-light leading-relaxed">{content}</p>
      </div>
    </section>
  );
}


/* ---------------- MAIN SLIDE 3 ---------------- */
/* Fullscreen background with diagonal ribbon for text */
export function MainSlide3({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] overflow-hidden bg-gradient-to-br from-green-900 via-emerald-800 to-green-700 flex items-center justify-center">
      {/* Background waves */}
      <svg
        className="absolute top-0 left-0 w-full h-full opacity-20"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 1440 320"
      >
        <path
          fill="#a7f3d0"
          fillOpacity="0.3"
          d="M0,160L80,144C160,128,320,96,480,85.3C640,75,800,85,960,117.3C1120,149,1280,203,1360,229.3L1440,256V0H0Z"
        ></path>
      </svg>

      {/* Abstract blobs */}
      <div className="absolute -top-32 -left-32 w-[500px] h-[500px] bg-green-400/20 rounded-full blur-3xl"></div>
      <div className="absolute bottom-0 right-0 w-[700px] h-[700px] bg-emerald-300/10 rounded-full blur-3xl"></div>
      <div className="absolute top-1/3 right-1/4 w-64 h-64 bg-green-500/30 rotate-12 rounded-[60%_40%_70%_30%/50%_60%_40%_50%] blur-xl"></div>

      {/* Doodle-like accent lines */}
      <svg
        className="absolute bottom-40 left-60 opacity-40"
        xmlns="http://www.w3.org/2000/svg"
        width="200"
        height="100"
        fill="none"
        stroke="#a7f3d0"
        strokeWidth="4"
        strokeLinecap="round"
      >
        <path d="M10 80 Q 60 20, 110 80 T 210 80" />
      </svg>

      {/* Text container */}
      <div className="relative z-10 text-center max-w-5xl px-24">
        <h2 className="text-7xl font-serif font-bold text-emerald-50 mb-8 drop-shadow-[0_4px_10px_rgba(0,0,0,0.4)]">
          {title}
        </h2>
        <p className="text-[2.7rem] text-emerald-100 leading-relaxed font-light">
          {content}
        </p>
      </div>

      {/* Decorative highlight bar */}
      <div className="absolute bottom-24 left-1/2 -translate-x-1/2 w-[300px] h-[5px] bg-emerald-300/80 rounded-full blur-[1px]"></div>
    </section>
  );
}

/* ---------------- MAIN SLIDE 2 ---------------- */
export function MainSlide2({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-green-50 flex flex-col items-center justify-center overflow-hidden">
      {/* Top Half: First Term */}
      <div className="absolute top-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full border-4 border-green-600 rounded-2xl bg-white/80 shadow-xl p-8 flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-bold text-green-900 mb-4">{title || 'Term 1'}</h2>
          <div className="h-[3px] w-32 bg-green-600 mb-6 rounded-full"></div>
          <p className="text-[2.5rem] text-green-800 leading-relaxed">{content || 'Definition for term 1'}</p>
        </div>
      </div>

      {/* Bottom Half: Second Term */}
      <div className="absolute bottom-[100px] left-0 right-0 h-[420px] px-20 z-10">
        <div className="h-full border-4 border-emerald-600 rounded-2xl bg-white/80 shadow-xl p-8 flex flex-col justify-center">
          <h2 className="text-6xl font-serif font-bold text-emerald-900 mb-4">{title2 || 'Term 2'}</h2>
          <div className="h-[3px] w-32 bg-emerald-600 mb-6 rounded-full"></div>
          <p className="text-[2.5rem] text-emerald-800 leading-relaxed">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>
    </section>
  );
}


/* ---------------- MAIN SLIDE 4 ---------------- */
/* Centered framed content with decorative leaf accents */
export function MainSlide4({ title, content, title2, content2 }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-green-100 flex items-center justify-center overflow-hidden">
      {/* Decorative leaf-like blobs */}
      <div className="absolute top-0 left-0 w-80 h-80 bg-green-400/30 rounded-full blur-3xl"></div>
      <div className="absolute bottom-0 right-0 w-96 h-96 bg-green-700/20 rounded-full blur-2xl"></div>

      {/* Left: First Term */}
      <div className="absolute left-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="border-4 border-green-600 rounded-2xl bg-white/80 shadow-xl p-10">
          <h2 className="text-6xl font-serif font-bold text-green-900 mb-6">{title || 'Term 1'}</h2>
          <div className="h-[3px] w-32 bg-green-600 mb-6 rounded-full"></div>
          <p className="text-[2.5rem] text-green-800 leading-relaxed">{content || 'Definition for term 1'}</p>
        </div>
      </div>

      {/* Right: Second Term */}
      <div className="absolute right-[100px] top-1/2 -translate-y-1/2 w-[800px] z-10">
        <div className="border-4 border-emerald-600 rounded-2xl bg-white/80 shadow-xl p-10">
          <h2 className="text-6xl font-serif font-bold text-emerald-900 mb-6">{title2 || 'Term 2'}</h2>
          <div className="h-[3px] w-32 bg-emerald-600 mb-6 rounded-full"></div>
          <p className="text-[2.5rem] text-emerald-800 leading-relaxed">{content2 || 'Definition for term 2'}</p>
        </div>
      </div>
    </section>
  );
}

/* ---------------- MAIN SLIDE 5 ---------------- */
/* ---------------- MAIN SLIDE 5 ---------------- */
/* Split horizontal bands with content overlay */
export function MainSlide5({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] flex items-center justify-center overflow-hidden bg-gradient-to-br from-green-800 via-emerald-600 to-lime-400">
      {/* Decorative blobs / waves */}
      <div className="absolute top-0 left-0 w-[900px] h-[900px] bg-emerald-400/30 rounded-full blur-3xl opacity-70 animate-pulse"></div>
      <div className="absolute bottom-0 right-0 w-[800px] h-[800px] bg-lime-300/30 rounded-full blur-3xl opacity-60 animate-pulse"></div>

      {/* Floating doodle-like shapes */}
      <div className="absolute top-10 right-40 w-40 h-40 bg-white/10 rounded-3xl rotate-12 backdrop-blur-xl shadow-lg"></div>
      <div className="absolute bottom-20 left-40 w-32 h-32 bg-green-100/10 rounded-full backdrop-blur-2xl shadow-md"></div>

      {/* Glassy content card */}
      <div className="relative z-10 backdrop-blur-2xl bg-white/20 border border-white/30 rounded-3xl shadow-2xl p-16 max-w-5xl text-center">
        <h2 className="text-7xl font-bold text-white drop-shadow-md mb-8 tracking-tight">
          {title}
        </h2>
        <p className="text-[2.7rem] text-white/90 leading-relaxed">
          {content}
        </p>
      </div>

      {/* Light reflection overlay */}
      <div className="absolute inset-0 bg-gradient-to-t from-transparent via-white/5 to-transparent"></div>
    </section>
  );
}



/* ---------------- MAIN SLIDE 6 ---------------- */
/* Split circle spotlight design */
export function MainSlide6({ title, content }) {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-b from-green-100 via-green-200 to-green-50 overflow-hidden flex flex-col justify-center items-center text-center">
      {/* Soft abstract waves */}
      <svg className="absolute bottom-0 left-0 w-full" viewBox="0 0 1920 500" fill="none">
        <path
          d="M0 300 C400 400 800 200 1200 300 C1600 400 1920 250 1920 250 L1920 500 L0 500 Z"
          fill="#bbf7d0"
          opacity="0.7"
        />
        <path
          d="M0 350 C500 450 1000 250 1500 350 C1700 390 1920 300 1920 300 L1920 500 L0 500 Z"
          fill="#86efac"
          opacity="0.6"
        />
        <path
          d="M0 400 C400 500 1000 300 1400 400 C1700 440 1920 320 1920 320 L1920 500 L0 500 Z"
          fill="#4ade80"
          opacity="0.5"
        />
      </svg>

      {/* Floating decorative elements */}
      <div className="absolute top-32 left-40 w-64 h-64 bg-green-300/30 rounded-full blur-3xl"></div>
      <div className="absolute top-10 right-20 w-48 h-48 bg-green-400/20 rounded-full blur-2xl"></div>

      {/* Text content */}
      <div className="relative z-10 max-w-5xl px-12">
        <h2 className="text-7xl font-serif font-bold text-green-900 mb-8 drop-shadow-sm">
          {title}
        </h2>
        <p className="text-[2.7rem] text-green-800 leading-relaxed tracking-wide">
          {content}
        </p>
      </div>
    </section>
  );
}



/* ---------------- IMAGE SLIDE ---------------- */
/* Split layout: left big image, right caption block */
export function ImageSlide({ title, content, autoGeneratedImage, imageUrl }) {
  const imageSrc = autoGeneratedImage || imageUrl;
  return (
    <section className="relative w-[1920px] h-[1080px] bg-green-50 flex">
      {/* Image side */}
      <div className="w-2/3 h-full overflow-hidden">
        {imageSrc ? (
          <img
            src={imageSrc}
            alt="Scholar Green visual"
            className="w-full h-full object-cover"
          />
        ) : (
          <div className="w-full h-full bg-green-200 flex items-center justify-center text-green-700">
            <div className="text-center">
              <div className="text-3xl font-serif font-bold mb-2">Auto Image Placeholder</div>
              <div className="text-xl">1st Term ImageSlide</div>
            </div>
          </div>
        )}
      </div>

      {/* Caption side */}
      <div className="flex-1 bg-green-700 flex flex-col justify-center p-12 text-white">
        <h3 className="text-3xl font-serif font-bold mb-4">{title}</h3>
        {content && (
          <p className="text-lg leading-relaxed opacity-90">
            {content}
          </p>
        )}
      </div>
    </section>
  );
}

export function TOCSlide({ tocData }) {
  // Handle both old format (items array) and new format (tocData object)
  const title = tocData?.title || "Table of Contents";
  const sections = tocData?.sections || [];
  
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-br from-[#f0fdf4] via-[#dcfce7] to-[#bbf7d0] text-[#064e3b] flex flex-col items-center justify-center overflow-hidden">
      {/* Subtle leaf accents */}
      <div className="absolute top-16 left-20 text-7xl text-green-600/30">🌿</div>
      <div className="absolute bottom-24 right-24 text-7xl text-green-700/30">📘</div>
      <div className="absolute top-1/2 left-1/3 -rotate-12 text-6xl text-green-500/20">🍃</div>

      {/* Decorative frame */}
      <div className="absolute inset-12 border-[6px] border-green-700/30 rounded-xl"></div>

      {/* Title */}
      <h2 className="text-6xl font-serif font-bold text-green-800 mb-16 drop-shadow-sm">
        {title}
      </h2>

      {/* Two-Column Layout for TOC - Minimized to show only main sections */}
      <div className="grid grid-cols-2 gap-20 z-10 max-w-6xl w-full">
        {/* Left Column */}
        <div className="space-y-10">
          {sections.slice(0, Math.ceil(sections.length / 2)).map((section, sectionIndex) => (
            <div key={sectionIndex} className="flex items-center gap-8 text-green-900 hover:text-green-600 transition-colors duration-300 group">
              <span className="w-20 h-20 flex items-center justify-center rounded-full bg-green-600 group-hover:bg-green-700 text-white font-bold text-2xl flex-shrink-0 border-3 border-green-200 group-hover:border-green-300 shadow-lg transition-all duration-300">
                {sectionIndex + 1}
                </span>
              <span className="text-5xl font-serif font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
            </div>
          ))}
        </div>

        {/* Right Column */}
        <div className="space-y-10">
          {sections.slice(Math.ceil(sections.length / 2)).map((section, sectionIndex) => {
            const actualIndex = Math.ceil(sections.length / 2) + sectionIndex;
            return (
              <div key={actualIndex} className="flex items-center gap-8 text-green-900 hover:text-green-600 transition-colors duration-300 group">
                <span className="w-20 h-20 flex items-center justify-center rounded-full bg-green-600 group-hover:bg-green-700 text-white font-bold text-2xl flex-shrink-0 border-3 border-green-200 group-hover:border-green-300 shadow-lg transition-all duration-300">
                  {actualIndex + 1}
                </span>
                <span className="text-5xl font-serif font-bold text-left leading-tight flex-1 group-hover:translate-x-2 transition-transform duration-300">{section.title}</span>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

// Keep old component for backward compatibility
export function TOCSlideScholarGreen({ title = "Table of Contents", items = [] }) {
  const tocData = {
    title,
    sections: items.map(item => ({ title: item, subsections: [] }))
  };
  return <TOCSlide tocData={tocData} />;
}

/* ---------------- END SLIDE ---------------- */
export function EndSlide() {
  return (
    <section className="relative w-[1920px] h-[1080px] bg-gradient-to-b from-emerald-900 to-green-700 flex flex-col items-center justify-center">
      <h1 className="text-5xl font-serif text-green-100 font-bold mb-4">
        End of Presentation
      </h1>
    </section>
  );
}

const ScholarGreen = {
  TitleSlide,
  TOCSlide,
  MainSlide1,
  MainSlide3,
  MainSlide4,
  MainSlide5,
  MainSlide6,
  ImageSlide,
  EndSlide,
};

export default ScholarGreen;
